### ISSUE TITLE
Add missing slayer monsters (Konar)

### ISSUE THREAD

**Issue by PTYB** [PTYB/SlayerIssueTracker#1]
Template:

**Note: Caps does matter**

> **Task name:**
> **Npc Name:**
> **Npc Location(Tile)**
> **Safespot?:**
> **Prayer recommended:**
> **Antipoison/Antifire:**
> **Slayer Gear/Additional requirements:**
> **Closest bank:**

**Comment by PTYB** [comment]
Comment missing tasks here only for Konar.

More information such as location/level/safespots/suggested method will help me add faster

**Comment by kneegr** [comment]
trolls in the troll stronghold "Mountain troll" are the npc names

**Comment by kneegr** [comment]
black demons in the chasm of fire, those are safespottable with ranged 

![Image](https://user-images.githubusercontent.com/127032135/222987508-e9db3e48-261b-497e-b518-b822e9e308f5.png)

**Comment by PTYB** [comment]
Added template for future posts

**Comment by Dyland0r** [comment]
Task name: Catacomb Greaters
Npc Name: Greater Demon
Npc Location: Catacombs of Kourend
Safespot: Possible
Prayer recommended: Yes, multi combat zone, don't need to pray with range safespotting, plausible to kill in just the melee zone higher combat level
Antipoison/Antifire: No
Slayer Gear/Additional requirements: Standard combat, no special requirements.
Closest bank:  Greater Kourend Bank, above the Catacombs.

![Kourend Greater Demons](https://user-images.githubusercontent.com/126752357/224534623-afb99692-3372-4350-a04b-33be904f30b8.png)

**Comment by PTYB** [comment]
@Dyland0r just added it, no safespot though. Will do next time I get the task.

**Comment by kneegr** [comment]
![image](https://user-images.githubusercontent.com/127032135/226194720-af918487-f70d-4e0d-83d1-2478985d349d.png)
Kalphite in the kalphite lair in al karid, the task only place has a real easy small area, doesnt need a safespot, its also cannonable, i have included a pic of the task name

**Comment by kneegr** [comment]
![Image](https://user-images.githubusercontent.com/127032135/226213181-17fcc151-7264-4dad-840a-ab8a31ac1a10.png)

can be either the baby or the big ones, they both have a safespot 



![Image](https://user-images.githubusercontent.com/127032135/226213976-7c156b6a-a495-45bd-8666-69070765f785.png)





![Image](https://user-images.githubusercontent.com/127032135/226214009-6b712b30-1a87-48d4-b0de-ce7e6a067083.png)

**Comment by PTYB** [comment]
@kneegr added Black dragons(couldnt test because not on task)

Is kalphite only task area a specific area thats assigned?

**Comment by PTYB** [comment]
Added more tasks

**Vannaka**

- Ice giants
- Green Dragon
- Pyrefiends
- Crocodile
- Ogre

**Comment by PTYB** [comment]
Added more tasks

**Vannaka**

- Hill giants
- Harpie Bug Swarm

**Konar** 

- Lizardman(Not shaman)

**Comment by PTYB** [comment]
Added more tasks

**Vannaka**

- Hobgoblin
- Ice warrior

**Konar**

- Catacombs  Firegiant
- Catacombs Brutal red dragons

**Comment by PTYB** [comment]
Added

Konar

- Slayer Tower AbberantSpectre

**Comment by PTYB** [comment]
Added

Konar

- Catacomb Deviant spectre
- Catacomb Mutated Bloodveld

**Comment by PTYB** [comment]
Added more tasks

**Vannaka**

- Wall Beasts

**Konar**

- Fossil Island Mutated Zygomites
- Karuulm Fire Giants

**Comment by PTYB** [comment]
Added more tasks

Vannaka

- Crawling Hands
- Bloodvelds

Konar

- Karaluum Greater Demon

**Comment by PTYB** [comment]
Added more tasks

**Vannaka**

-  Turoth - Fremenick slayer caves
- Feral Vampyre - Haunted Woods
- Loar Shade - Morton

**Konar**

-  Brutal black dragons Catacombs

**Comment by PTYB** [comment]
Added more tasks

**Konar**

- BrineRats
- Ankou in stronghold slayer

**Vannaka**

- Ghouls in Canifis
- Banshees at Slayer Tower

**Comment by PTYB** [comment]
Added

**Vannaka**

- Basilisk in Freminick slyayer cave
- Otherworldly Beings in Zanaris
- Bronze dragen in Brimhaven

**Comment by skuffed** [comment]
Task name: greater demons in the Chasm of Fire
Npc Name: Greater demon
Npc Location(Tile): Tile(x=1430, y=10079, floor=2, localX=46, localY=55)
Safespot?: Tile(x=1423, y=10078, floor=2, localX=39, localY=54)
Prayer recommended: no they are just greater demons
Antipoison/Antifire: no
Slayer Gear/Additional requirements: 
Closest bank: Shayzien encampment

**Comment by Zargha1** [comment]
Task name: trolls on Death Plateau
Npc Name: Troll
Npc Location(Tile): 2874, 3594, 0
Safespot?: Yes 2870, 3580, 0
Prayer recommended: No
Antipoison/Antifire: No
Slayer Gear/Additional requirements:
Closest bank: Burthope, Rogues den bank

**Comment by Zargha1** [comment]
Task name: dust devils in Catacombs of Kourend
Npc Name: Dust Devil
Npc Location(Tile): 1714, 10032, 0 (small area) OR 1712, 10015, 0 (big area, usually someone bursting)
Safespot?: No
Prayer recommended: Yes, melee
Antipoison/Antifire: No
Slayer Gear/Additional requirements: Facemask
Closest bank: Kourend

**Comment by PTYB** [comment]
What  location is the name of those fire giants @Zargha1 ?

**Comment by PTYB** [comment]
Dust devils will be added next task

**Comment by Zargha1** [comment]
Waterfall Dungeon, edited og post @PTYB

**Comment by PTYB** [comment]
- Fixed Zygomite
- Added Lizardman in Kebos swamp
- Added Dust Devils in Catacombs of Kourend

**Comment by PTYB** [comment]
To be deployed 

- Fix for infernal mages
- Catacombs of Kourend Dagganoths added

**Comment by Enskauning** [comment]
Task name: God wars dungeon bloodvelds
    Npc Name: bloodveld
    Npc Location(Tile)
    Safespot?: no 
    Prayer recommended: no
    Antipoison/Antifire: no
    Slayer Gear/Additional requirements: no
    Closest bank: edgeville maybe?

**Comment by Litag10** [comment]
Task name: Green dragons in Brimhaven Dungeon
Npc Name: Baby green dragon
Npc Location(Tile) x=2657, y=9571, floor 2, localx=57. localy: 51 
Safespot?:x=2655, y=9570, floor 2, localx=55. localy: 50 
Prayer recommended:
Antipoison/Antifire: no
Slayer Gear/Additional requirements: no
Closest bank: ardy?

**Comment by Enskauning** [comment]
Task name: Hellhounds in Karuulm Slayer Dungeon
    Npc Name: Hellhounds
    Npc Location(Tile) Karuulm Slayer Dungeon
    Safespot?:
    Prayer recommended:
    Antipoison/Antifire:
    Slayer Gear/Additional requirements: Boots of stone, Boots of Brimstone, Granite boots
    Closest bank: Mount Karuulm bank

**Comment by Enskauning** [comment]
https://gyazo.com/cf0dd98393cd68f042d62baacfce39ca

**Comment by Litag10** [comment]
Task name: Blue dragon
Npc Name: Baby blue dragon 
Npc Location(Tile)(x=2898, y=9765, floor=0, LocalX=58, LocalY=37) 
Safespot?: 
Prayer recommended:
Antipoison/Antifire: Antifire
Slayer Gear/Additional requirements: agility lvl 70 or dusty key
Closest bank: falador west
![Screenshot_20230617_214932](https://github.com/PTYB/SlayerIssueTracker/assets/128861755/c9584b88-d8f0-4604-ad35-2e4676acfdd7)

**Comment by PTYB** [comment]
That is not konar and it is not misisng. Only Konar is supported and it does support blue dragons.

**Comment by Litag10** [comment]
> That is not konar and it is not misisng. Only Konar is supported and it does support blue dragons.

Ah ok, I was thinking it was ok since you added alot of vannaka tasks here.

**Comment by Enskauning** [comment]
https://gyazo.com/bdece3cfcbbef6d4c5b812d37d1268c2

**Comment by Enskauning** [comment]
Task name: Red Dragons
    Npc Name: Red Dragon
    Npc Location(Tile)
    Safespot?:
    Prayer recommended:
    Antipoison/Antifire: Antifire
    Slayer Gear/Additional requirements: Antifire shield
    Closest bank: Dunno

https://gyazo.com/6a400b2c288748fc4877ab832d676e70

**Comment by PTYB** [comment]
Added Forthos red dragons
Added Battlefront lizardman

**Comment by Rallik-Pog** [comment]
Task name: Waterfiends in the Iorwerth Dungeon
    Npc Name: Waterfiend 
    Npc Location(Tile): See attached.
    Safespot?: No
    Prayer recommended: TBD, Magic if any. 
    Antipoison/Antifire: No
    Slayer Gear/Additional requirements: SOTE Quest, Dungeon is located in south-west Prifddinas. Waterfiends use Magic / Magical Ranged attacks, dragonhide or magic defense recommended. They are VERY weak to crush attacks.
    Closest bank: Prifddinas South-East bank


![Image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/ac5f7e8f-dc8f-4e2a-80c4-4eb3a54694a4)
![Image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/ec6bc954-5332-46d0-bfc3-60e0f7af38fd)
![Image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/2779c35e-c499-444f-9544-c68e9d496c53)

**Comment by Rallik-Pog** [comment]
Task name: Skeletal Wyverns in Asgarnian Ice Dungeon
    Npc Name: Skeletal Wyvern
    Npc Location(Tile) 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/44832189-74b7-417d-a7c2-1dfe39e7adba)

    Safespot?: There are but its a pain to setup; I would say no.
    Prayer recommended: Pray Range and stand away if mage/range. They melee you if you are close. You can pray melee as melee. Great gear and stats you dont really need prayer.
    Antipoison/Antifire: Require a antifire shield or mind shield/elemental shield. Antifire potions do not work.
    Slayer Gear/Additional requirements: 72 slayer, 70 combat, elemental workshop 1
    Closest bank: Fairy ring -- or draynor village/crafting guild.

**Comment by Rallik-Pog** [comment]
Task name: Black Dragons in Evil Chicken's Lair
    Npc Name: Black Dragon
    Npc Location(Tile): This is also safespot tile.
    ![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/816173c7-dd60-470b-8831-3c918f4283d0)
    Safespot?: Yes for mage/range in the east tunnel leading to the mining area.

    Prayer recommended: TBD
    Antipoison/Antifire: Antifire yes
    Slayer Gear/Additional requirements: 80 combat partial completion of dragon slayer 1 / access to Zanaris / recipe for disaster? https://oldschool.runescape.wiki/w/Evil_Chicken%27s_Lair
    
   you need to use a raw chicken on the statue to enter the lair

    Closest bank: Zanaris

**Comment by Rallik-Pog** [comment]
Task name: Black Dragons at Myths' Guild Dungeon
    Npc Name: Black Dragon
    Npc Location(Tile): 
    Safespot?: Yes
    Prayer recommended: No
    Antipoison/Antifire: No
    Slayer Gear/Additional requirements: Dragonslayer 2
    Closest bank: Myths Guild Chest

**Comment by Rallik-Pog** [comment]
Task name: Bloodveld in God Wars Dungeon
    Npc Name: Bloodveld
    Npc Location(Tile) TBD
    Safespot?: TBD
    Prayer recommended: TBD
    Antipoison/Antifire: No
    Slayer Gear/Additional requirements: Maybe climbing boots or trollheim teleport for GWD access
    Closest bank: TBD

**Comment by Rallik-Pog** [comment]
Task name: Bloodveld in the Meiyerditch Laboratories
    Npc Name: Bloodveld
    Npc Location(Tile): TBD  
    Safespot?: TBD
    Prayer recommended: N/A - can be to stay down longer.
    Antipoison/Antifire: no
    Slayer Gear/Additional requirements: Sins of our father quest completed or started. **If completed fairy ring DLS to trueblood and run south to bloodvelds**
    Closest bank: Mort myre swamp

![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/c1e01f72-736a-410c-bde8-9a2ddc021673)

**Comment by Rallik-Pog** [comment]
> * Fixed Zygomite
> 
>     * Added Lizardman in Kebos swamp
> 
>     * Added Dust Devils in Catacombs of Kourend

Some reason its Dust Devils are no longer on the list 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/bc543b38-f68a-4e05-afaf-abc9f4a33efc)

**Comment by Rallik-Pog** [comment]
> Dust

For some reason this is now unsupported for Konar. @PTYB

**Comment by PTYB** [comment]
Dust devils are back now

**Comment by PTYB** [comment]
> Myths' Guild Dungeon

Can I please have the bank tile for this?

**Comment by PTYB** [comment]
All added but myths guild

**Comment by PTYB** [comment]
Adding myths guild now

**Comment by PTYB** [comment]
Added 
* troll stronghold trolls
* GWD Aviansies

**Comment by PTYB** [comment]
Closing this megathread, create new tickets with info in future ones
