### ISSUE TITLE
Add Default Light Source (Candle Lantern + Tinderbox)

### ISSUE THREAD

**Issue by Savage-FoL** [PTYB/SlayerIssueTracker#100]
Candle Lantern is a closed Light source and the only way it goes out is if you fall into the water, so adding a + tinderbox support to light it back up would be amazing

Requirements to light it is only 4 Firemaking (7 Logs to get 4 FM) so anyone can easily get access to it.

**Comment by PTYB** [comment]
Added candle+bullseye in latest, although candle seems to explode alot.
