### ISSUE TITLE
Ignores Inventory Setup for Ankou Task

### ISSUE THREAD

**Issue by Savage-FoL** [PTYB/SlayerIssueTracker#101]
Issue: When Task is Ankou, ignores inventory setup
Current behavior: Bot checks what task it has with Gem, then immediately starts walking to Ankou without setting up Inventory
Expected behavior: Fix equipment + Withdraw Food and Potions to fight Ankous with
Screenshots/Video:
Additional information: Bot doesn't check to see equipment or Inventory, just starts walking to Ankou location.

**Comment by PTYB** [comment]
Need inventory setup.
