### ISSUE TITLE
Bot gets stuck trying to pick up loot at the wrong tile

### ISSUE THREAD

**Issue by powbotthrowaway** [PTYB/SlayerIssueTracker#102]
Issue: Bot gets stuck trying to pick up loot at the wrong tile
Current behavior:  Spam clicks the wrong tile when trying to pick up items from the ground.
Expected behavior:  Pick up items from the correct tile.
Screenshots/Video: https://storage.googleapis.com/openscreenshot/Y%2Fx%2Fg/k0XWEcgxY.png (the wrong tile it spams is being highlighted in red)

**Comment by PTYB** [comment]
Thats a weird one, is this constant? Where did the black demon die?

**Comment by powbotthrowaway** [comment]
No it's not constant.  The items were next to the lava pool.  Basically where the bot is standing in the screenshot.

I tried zooming in and out.  As id zoom in, the red marker would get closer to the actual tile.  Zooming out made it get further away.
For this reason, I suspect this might be some tile projection issue.

Not sure if this is a script related or client related responsibility.

**Comment by powbotthrowaway** [comment]
Resolving because I was able to reproduce, and I think I figured out the issue.

Orientation switching messes up the tile projection.  This may be a client issue.  If it happens again with orientation lock, I'll reopen.
