### ISSUE TITLE
[Bug] Blue Dragon - Ogre Enclave

### ISSUE THREAD

**Issue by Djumi123** [PTYB/SlayerIssueTracker#105]
Issue: 
- Gets stuck in loop of entering and leaving the ogre enclave.

Current behavior:
- always enters the cave then walks to the exit, runs over the mountain and joins the cave again.

Expected behavior:
- Runs to the safespot when entering the cave.

Screenshots/Video:
- None

Additional information:
- had to walk manualy close to the safespot and restart, then it worked.

**Comment by PTYB** [comment]
Logs?

**Comment by PTYB** [comment]
Closed until logs provided
