### ISSUE TITLE
Possibility to add safespots for certain npcs

### ISSUE THREAD

**Issue by Tosccony** [PTYB/SlayerIssueTracker#106]
Current behavior: Places cannon down and fights npcs.

Expected behavior: If possible I would like to be able to safespot while ranging, would turn on prayer to refill cannon and return to the safespot location and turn off prayer and kill the npcs from the the safespot tile.

Screenshots/Video:
![fire_giant_safespot](https://github.com/PTYB/SlayerIssueTracker/assets/148006350/0cd4db3d-fdb4-4ba2-8182-4252b1d1f021)

Additional information: By placing the cannon down and going to the safespot it allows you to multi target the fire giants with the cannon and overtime you get more xp/hr and save on prayer pots, there's more locations for other npcs aswell that you can do the same thing. If it's something that would be doable I can get you screenshots with the locations and anything else that would be needed.

**Comment by PTYB** [comment]
I had thought about adding safespots, although it's hard to query which NPC to attack and special logic. If you send me the tile coordinates I could add something for you(Not the prayer while running in etc)

**Comment by Tosccony** [comment]
Hey, here's a list with spots I've found so far. I used Proto's Fighter script for the tiles, if they aren't accurate I can figure out a better way to get them for you.

Npc: Hellhounds

Safespot location: X: 2419 , Y: 9784, Floor : 0

Cannon location: Same location

Screenshot:
![Hellhounds](https://github.com/PTYB/SlayerIssueTracker/assets/148006350/2466c2b5-5fc3-4653-98e7-235382d77f5f)

Additional Information:




Npc: Fire Giant

Safespot location: X: 2407, Y: 9778, Floor: 0

Cannon location: X: 2401, Y: 9780, Floor: 0

Screenshot:
![Fire giant cannon](https://github.com/PTYB/SlayerIssueTracker/assets/148006350/e45c44b8-1c11-47d1-b9ed-280468a62947)


Additional Information: With the location change for the cannon it allows double hits and seems to do better overall with killing.

**Comment by Tosccony** [comment]
Npc:Bloodvelds

Safespot location: X: 2458, Y: 9822, Floor: 0

Cannon location: X: 2453, Y: 9817, Floor: 0

Screenshot:
![Screenshot_20231018_201313](https://github.com/PTYB/SlayerIssueTracker/assets/148006350/5ac9c30b-4b0c-4685-b94b-fa4b88297dae)



Additional Information: Cannon location is a little different to accommodate for safespot location, it can also hit bloodvelds in the first room.




Npc: Greater Demon

Safespot location: X: 1434, Y: 10086, Floor: 2

Cannon location: X: 1435, Y: 10085, Floor: 2

Screenshot:
![Screenshot_20231017_223242](https://github.com/PTYB/SlayerIssueTracker/assets/148006350/80deb449-70ce-437b-a3f0-7b6140cb8c93)




Additional Information: This is a nice spot , it allows safespotting with the cannon right beside you for easy refilling

**Comment by Tosccony** [comment]
Npc: Black Demons - Chasm of Fire

Safespot location: X: 1437, Y: 10095, Floor: 1

Cannon location: X: 1438, Y: 10090, Floor: 1

Screenshot:
![Black demons](https://github.com/PTYB/SlayerIssueTracker/assets/148006350/61dde053-d0bf-4911-9ec6-d135c0f48211)



Additional Information: So I couldn't find a great spot and this is the best I could find and averaged about 25-30k slayer xp at this location, the way it is setup now is that the cannon is across the room from the current safespot, there's probably a better location but haven't found one yet.

Npc: Kurask - Fremennik Slayer Dungeon

Safespot location: Need to grab location

Cannon location: N/A

Screenshot:
![Kurask Safespot](https://github.com/PTYB/SlayerIssueTracker/assets/148006350/bbf76738-a3a6-4949-bc85-0030a6087d3c)



Additional Information: I don't believe Kurask has a safespot added at the moment, while I was on task I did find a spot.

**Comment by PTYB** [comment]
I thought ogres already had the safespot, will look at adding more

**Comment by PTYB** [comment]
Added fire giants

Will do the following later

- Hellhounds
- Greater demons
- Kurask

Bloodvelds/Black demons will have to wait until I do regions inside areas

**Comment by PTYB** [comment]
Added safespot for hellhounds

**Comment by Tosccony** [comment]
Awesome thanks!

**Comment by PTYB** [comment]
Just FYI @Tosccony I am currently working on regions(Should be this weekend) and I will add the remaining bloodveld safespot. Hopefully this will make it less intrusive for real players and cause better exp/hr

**Comment by PTYB** [comment]
Bloodvelds released

**Comment by Tosccony** [comment]
Thanks! I'll be running some accounts through sometime this week. I'll let you know if there's any issues!
