### ISSUE TITLE
Antipoison totally broken

### ISSUE THREAD

**Issue by Laddad123** [PTYB/SlayerIssueTracker#107]
Found a new problem with Cave crawlers, it'll withdraw the whole inventory full off food instead and just stay there in bank til it stops.
Antipoison seems broken :/ 

Script: Slayer
Problem: Found a issue with cave slims assignment. When assigned a cave slime task, no matter how I changed the settings with antipoisons the script would withdraw 19 foods instead of the number chosen, and the script will withdraw antipoisons then stop saying it's missing antipoison 4 (1) even tho it's not chosen. If I put antipoison 4 to inventory it'll withdraw 3, then deposit 2, withdraw 2, deposit 2 in an endless loop.

Edit: I completely removed antipoison from inventory on the config for cave slimes as the task is so short, and now it withdraws 1 antipoison (4) only and works fine.

**Comment by Laddad123** [comment]
I removed the food from the specific Cave crawlers, saved it, then it worked for the crawlers. But I believe something is still messed because of the antipoison

**Comment by PTYB** [comment]
Did the fix resolve your issue?

**Comment by Laddad123** [comment]
> Did the fix resolve your issue?

Yes it's fixed!
