### ISSUE TITLE
New Location for Bloodvelds

### ISSUE THREAD

**Issue by TrippyBbPie** [PTYB/SlayerIssueTracker#111]
Meiyerditch Laboratories Location after Song of the elves quest is an insane exp/h cannonable/multi combat mutated bloodveld spot. Use melee + prayer and its an amazing task location. If you need any other info lemme know.

**Comment by PTYB** [comment]
Need tiles + areas etc.

**Comment by PTYB** [comment]
Closed until tiles/area etc is supplied, feel free to re-open
