### ISSUE TITLE
Killed current enemy while looting last enemy, it will not register/loot the current enemy when it dies.

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#114]
Spoke about this in discord Dm's

If it kills NPC B while looting NPC A, it will not loot or register NPC B's loot.

**Comment by PTYB** [comment]
Not really a bug but I can add an enhancement to loot after kill in the future.

**Comment by PTYB** [comment]
Duplicate of https://github.com/PTYB/SlayerIssueTracker/issues/98
