### ISSUE TITLE
Standing in edge bank

### ISSUE THREAD

**Issue by TrippyBbPie** [PTYB/SlayerIssueTracker#115]
Standing in edge bank saying "Go to bank" on wyrms task. 

[slayer.txt](https://github.com/PTYB/SlayerIssueTracker/files/13102977/slayer.txt)

EDIT: Found out why it stands there, It opens mage book trying to tele to house. But when i put runes into invent it goes on an endless loop to bank in edge.

**Comment by PTYB** [comment]
Did you set it to tele to house?

**Comment by TrippyBbPie** [comment]
for the task i was on yes but it would use runes instead of tele tabs. If i had tele tabs it would still try opening mage book and try using the actual "Teleport to house" spell rather than using tabs. Once i got runes, it would tele to house.. use rejuv pool and then use glory to go back to edge to bank and repeat that whole cycle.

**Comment by PTYB** [comment]
Should be fixed in latest, please test in house

**Comment by TrippyBbPie** [comment]
Your fix with the runes worked. Tested and everything went good! ty!
