### ISSUE TITLE
Elves task not supported

### ISSUE THREAD

**Issue by TrippyBbPie** [PTYB/SlayerIssueTracker#117]
Issue: Elf Task not supported
Current behavior: Script completely stops without any errors. 
Expected behavior: Go to Iowerth Camp (cannonable), Lletya location (need to start mournings end part 1), Or Iowerth Dungeon (song of the elves quest) 
Screenshots/Video: N/A
Master: Nieve
Task: Elves
Additional information:

**Comment by PTYB** [comment]
Can you start using the template. Its there for a reason.

https://github.com/PTYB/SlayerIssueTracker/blob/main/README.md

**Comment by TrippyBbPie** [comment]
my bad forgot there was one. lol will edit posts when i get home from work.

**Comment by PTYB** [comment]
Elves should be added now
