### ISSUE TITLE
[Bug] Gargoyle left at 0hp

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#118]
Issue: Leaves Gargoyle's at 0hp without stone hammering and moves on to the next target
Current behavior: leaves at 0hp without stone hammering. (i have the slayer reward for auto hammering aswell.)
Expected behavior: finish the kill before moving onto the next
Screenshots/Video: https://youtu.be/kFA2fTVePn4?feature=shared
Master: Konar
Task: Gargoyle Slayer Tower
Additional information:

**Comment by PTYB** [comment]
Fixed in 0.0.41

**Comment by PTYB** [comment]
Closing, feel free to re-open if issues
