### ISSUE TITLE
[Bug] Leaving Lighthouse

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#119]
Issue: After finishing daggonoth task under lighthouse, it has trouble leaving to go get another task. even with teleport options to go out.
Current behavior: climbs up ladder, exits through door & then spam clicks the iron ladder on the other side of the door back down to daggonoths.
Expected behavior: Teleport out with ardy cloak instead of walking out.
Screenshots/Video: 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/c8abcc51-7875-4e6c-b7dc-7ae8287dc567)

Master: Konar
Task:  Daggonoths in the lighthouse.
Additional information:

**Comment by PTYB** [comment]
As discord thread is closedd I will close this - https://discordapp.com/channels/341014842745815054/1174402646417879101
