### ISSUE TITLE
[Enhancement] Slayer ring (eternal)

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#120]
Current behavior: Slayer ring (eternal) not supported by powdax
Expected behavior: Utitlize Slayer Ring teleports.
Screenshots/Video: 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/1665fcee-0dde-48f5-96b9-fa1eefd2ac66)
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/5e4ef562-012b-4406-94ce-54340f7e989d)

**Comment by PTYB** [comment]
Refer to this since its dax/client - https://discordapp.com/channels/341014842745815054/1174413254446022700
