### ISSUE TITLE
[Bug][Client?] Trying to click through current Ammo

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#121]
Issue: tries to pickup loot through the ammo overlay.
Current behavior: tries to spamclick to pickup loot through ammo overlay.
Expected behavior: move camera or move since ammo overlay is unable to be clicked through.

![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/f8a3fb6b-4cf5-41ec-9677-376d0f066188)

**Comment by PTYB** [comment]
Client issue, raise a client bug
