### ISSUE TITLE
[Bug] Cannon Re-fireing after reloading.

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#122]
Issue: Sometimes with massive amounts of enemys, it does not reload intime before it runs out of ammo. It does not re-fire the cannon to get it going again.
Current behavior: Does not re-fire the cannon if it doesnt get reloaded intime.
Expected behavior: Refire the cannon or reload the cannon earlier?
Additional information: This only happens on high volume mobs. Its usually running around looting & does not make it in time to reload.

**Comment by PTYB** [comment]
Will have to work on a timeout option for this

**Comment by PTYB** [comment]
Should have been resolved with last release
