### ISSUE TITLE
Withdrawing to little coins for Brimhaven when using Monastery teleport.

### ISSUE THREAD

**Issue by Laddad123** [PTYB/SlayerIssueTracker#123]
Issue: Withdrawing 875 coins from Tzhaar bank, then teleports to Monastery, takes the boat to Brimhaven and gets stuck at entrance cus it misses 30 coins. Found myself stuck there the other day.
Current behavior: As expected above
Expected behavior: Setting it to withdraw 905 coins instead of 875 as standard could be a good idea I guess? 
Screenshots/Video: 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/148270453/a97abd30-8d1a-488f-be02-b4cd846411d7)
 (Only ss on setup, think one from cave is not needed.)
Master: Any
Task: Brimhaven dungeon tasks
Additional information: I mean it's easily fixed by changing the amount yourself on every task that goes to brimhaven, but I believe it would be a pretty easy thing to change to avoid people getting stuck that doesn't know about it

**Comment by PTYB** [comment]
Tzhaar bank doesn't really need coins, but can update.

**Comment by Rallik-Pog** [comment]
The issue is if its using ardounge cloak, it will take the boat first.

**Comment by PTYB** [comment]
Should default to 905 now

**Comment by Laddad123** [comment]
Its done!
