### ISSUE TITLE
New issue with Falador portal

### ISSUE THREAD

**Issue by TrippyBbPie** [PTYB/SlayerIssueTracker#124]
Issue: Long tap/holding on fally portal (could be all portals but happening to fally atm)
Current behavior: Opening portal interface constantly but not actually teleporting.
Expected behavior: Single click on portal
Screenshots/Video:  https://gyazo.com/80133df1957d3abdd2c13e87901c5260
Master: Nieve
Task: Black Demons Taverly dungeon
Additional information: Logs attached, Also when manually clicking fally portal it teles back to home and repeats the process again.
[slayer.txt](https://github.com/PTYB/SlayerIssueTracker/files/13170874/slayer.txt)

**Comment by PTYB** [comment]
Should be fixed in 0.0.41 (1/2 mins)

**Comment by TrippyBbPie** [comment]
Yes, fixed. Camelot one is fixed as well. Thanks!
