### ISSUE TITLE
Wyverns task not supported

### ISSUE THREAD

**Issue by TrippyBbPie** [PTYB/SlayerIssueTracker#125]
Issue: Wyverns task not supported
Current behavior: Script stops with no error. Not configured in script.
Expected behavior: Do wyverns task, Skeletal Wyverns as well, Fossil Island either between Spitting Wyvern, Taloned Wyvern. Long-tailed Wyvern
Screenshots/Video: N/A
Master: Nieve
Task: Wyverns
Additional information:

**Comment by PTYB** [comment]
Will do the quests to unlock it

**Comment by PTYB** [comment]
Added wyverns task

**Comment by PTYB** [comment]
As per https://github.com/PTYB/SlayerIssueTracker/issues/141 I assume its working(Except farcasting, closing.
