### ISSUE TITLE
Spiritual Creatures not supported

### ISSUE THREAD

**Issue by TrippyBbPie** [PTYB/SlayerIssueTracker#126]
Issue: No config for Spiritual Creatures
Current behavior: Script stops because of no config
Expected behavior: Teleport to trollheim (if youve done the quest) Go to godwars dungeon to kill them. 
Screenshots/Video:
Master: Nieve
Task: Spiritual Creatures
Additional information: Probably range them using 1 piece of each godwars race dhide just to make it easier. Prot from mage (killing mages obviously lol)

**Comment by PTYB** [comment]
I will have to do the quests to unlock this. Is there a preferred NPC for non 83 slayer?

**Comment by PTYB** [comment]
Added to .46, will add trollheim method this weekend. Also requires teleport out
