### ISSUE TITLE
Script wont grab new tasks

### ISSUE THREAD

**Issue by TrippyBbPie** [PTYB/SlayerIssueTracker#127]
Issue: Script ends after task completes. Wont grab a new task.
Current behavior: ^^^^
Expected behavior: Get new task after completing current task.
Screenshots/Video: Current task area completed - https://gyazo.com/674d72ca7a4322b291191e04284bf9c1
Master: Nieve
Task: None but just finished Fire Giants
Additional information: logs attached
[slayer.txt](https://github.com/PTYB/SlayerIssueTracker/files/13194213/slayer.txt)

**Comment by PTYB** [comment]
Should be resolved now

**Comment by PTYB** [comment]
Assuming all good because it works for me and nothing posted. Let me know if its not the case
