### ISSUE TITLE
[Bug] POH nexus menu

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#130]
10-31 15:06:48.684  4141  9921 W System.err: java.util.NoSuchElementException: Array contains no element matching the predicate.
10-31 15:06:48.684  4141  9921 W System.err:    at com.pty.slayer.logic.inhouse.leafs.TeleportInHouse.portalNexusTeleport(TeleportInHouse.kt:117)
10-31 15:06:48.684  4141  9921 W System.err:    at com.pty.slayer.logic.inhouse.leafs.TeleportInHouse.execute(TeleportInHouse.kt:53)
10-31 15:06:48.684  4141  9921 W System.err:    at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
10-31 15:06:48.684  4141  9921 I chatty  : uid=10136(com.jagex.oldscape.android) pool-34-thread- identical 8 lines
10-31 15:06:48.684  4141  9921 W System.err:    at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
10-31 15:06:48.684  4141  9921 W System.err:    at org.powbot.api.script.tree.TreeScript.poll(TreeScript.kt:19)
10-31 15:06:48.684  4141  9921 W System.err:    at org.powbot.mobile.script.ScriptManager$runScript$3.invokeSuspend(ScriptManager.kt:500)
10-31 15:06:48.684  4141  9921 W System.err:    at org.powbot.mobile.script.ScriptManager$runScript$3.invoke(Unknown Source:8)
10-31 15:06:48.684  4141  9921 W System.err:    at org.powbot.mobile.script.ScriptManager$runScript$3.invoke(Unknown Source:4)
10-31 15:06:48.684  4141  9921 W System.err:    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
10-31 15:06:48.684  4141  9921 W System.err:    at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
10-31 15:06:48.684  4141  9921 W System.err:    at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
10-31 15:06:48.684  4141  9921 W System.err:    at org.powbot.mobile.script.ScriptManager.runScript(ScriptManager.kt:498)
10-31 15:06:48.684  4141  9921 W System.err:    at org.powbot.mobile.script.ScriptManager.access$runScript(ScriptManager.kt:48)
10-31 15:06:48.684  4141  9921 W System.err:    at org.powbot.mobile.script.ScriptManager$start$3.invokeSuspend(ScriptManager.kt:231)
10-31 15:06:48.684  4141  9921 W System.err:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-31 15:06:48.684  4141  9921 W System.err:    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
10-31 15:06:48.684  4141  9921 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-31 15:06:48.684  4141  9921 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-31 15:06:48.684  4141  9921 W System.err:    at java.lang.Thread.run(Thread.java:923)
10-31 15:06:48.684  4141  9921 I FlagManager:  [pool-34-thread-1] 10-31 15:06:48.684  INFO FlagManager - Updating key current_script to value
10-31 15:06:48.686  4141  9921 I FlagManager:  [pool-34-thread-1] 10-31 15:06:48.686  INFO FlagManager - Updating key script_state to value Stopped

Script stops when opening nexus. Unable to port from nexus to ardounge.

**Comment by PTYB** [comment]
Fixed in .45
