### ISSUE TITLE
Infernal mages wrong prayer setup.

### ISSUE THREAD

**Issue by Laddad123** [PTYB/SlayerIssueTracker#131]
Issue: Bot is using pray against melee against Infernal mages, almost died cus of that, but the monastery tp saved me.
Current behavior: As described
Expected behavior: Pray against Magic
Screenshots/Video: 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/148270453/0689888f-4772-4740-a9cc-9414c2080523)

Master: Vannaka
Task: Infernal Mages
Additional information:  Guess not much more info is needed?

**Comment by PTYB** [comment]
Fixed in .45
