### ISSUE TITLE
Task spot missing,

### ISSUE THREAD

**Issue by Laddad123** [PTYB/SlayerIssueTracker#132]
Issue:Bloodvelds god wars dungeon spot missing 
Current behavior: Script stops immediately as it doesnt exist in config	
Expected behavior: Killing bloodvelds in the godwars dungeon
Screenshots/Video: 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/148270453/82a5a5f8-920b-48bc-8c69-0b80f883acc3)

Master: Konar	
Task: Bloodveld (God wars dungeon)
Additional information: Nada

**Comment by PTYB** [comment]
Will be added when I get task

**Comment by PTYB** [comment]
Added to .46, will add trollheim method this weekend. Also requires teleport out

**Comment by PTYB** [comment]
Closing, reopen if theres issues
