### ISSUE TITLE
Webwalker/script can't find the way to mos le'harmless?

### ISSUE THREAD

**Issue by Laddad123** [PTYB/SlayerIssueTracker#134]
Issue: Script can't find the way to mos'le harmless
Current behavior: First had issue where it wouldn't move at all but added coins so it can take charter ship, problem is it gets stuck at the charter ship, other ships are fine but wont find it's way to mos.
Expected behavior: Actually getting there
Screenshots/Video: ![image](https://github.com/PTYB/SlayerIssueTracker/assets/148270453/3734e86d-491e-4629-bb18-877bc9575ab5)
Master: Nieve
Task: Cave Horror
Additional information:

Do I need an ectophial?

**Comment by Laddad123** [comment]
Ah, I added some coins for it to take the boat/charter ship there and it works. Seems you need to do that or get an ectophial to get there!

**Comment by Laddad123** [comment]
![image](https://github.com/PTYB/SlayerIssueTracker/assets/148270453/08a0cb3b-38f0-4c17-bd50-3ee36642552f)
It simply gets stuck at charter ship.

**Comment by PTYB** [comment]
Should be fixed in beta build soon.

**Comment by PTYB** [comment]
Re-open if issues.
