### ISSUE TITLE
[Enhancement] More bank support! 

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#135]
Lacking alot of banks, Grand Exchange, etc. Potentially add use closest bank to teleport?

![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/f27ebf2b-c46d-4847-a4b8-39a1cadbd4c5)

**Comment by PTYB** [comment]
State which are missing with tiles, nearest is not easy from POH

**Comment by PTYB** [comment]
Added all from our private messages? Good to close?

**Comment by Rallik-Pog** [comment]
Yeah thank you!
