### ISSUE TITLE
Tzhaar task not attacking npcs

### ISSUE THREAD

**Issue by TrippyBbPie** [PTYB/SlayerIssueTracker#137]
Issue: Tzhaar Task not working correctly
Current behavior: Script says killing NPCS and standing at fairy ring after teleporting to tzhaar city
Expected behavior: Go to scripted spot and kill tzhaar NPC's
Screenshots/Video: ![image](https://github.com/PTYB/SlayerIssueTracker/assets/148507398/3f31deec-1842-4adc-8c60-b41f754c8ae7)
Master: Nieve
Task: tzhaar
Additional information: 
[slayer.txt](https://github.com/PTYB/SlayerIssueTracker/files/13326969/slayer.txt)

**Comment by PTYB** [comment]
Fix should be released soon
