### ISSUE TITLE
[Konar] Blue Dragons in Myths' Guild Dungeon

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#142]
Task name: Blue Dragons in Myths' Guild Dungeon
    Npc Name: Blue dragon
    Npc Location(Tile): 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/ae8e299b-7dc7-4c34-a267-c3dcbd78c43d)
    Safespot?: Yes, tile above.
    Prayer recommended: no
    Antipoison/Antifire: Yes antifire shield.
    Slayer Gear/Additional requirements: Dragon Slayer 2
    Closest bank: Myths guild.

**Comment by PTYB** [comment]
Will be added in next release

**Comment by PTYB** [comment]
Closing cuz no complaint
