### ISSUE TITLE
[Konar] Red Dragons in Myths' Guild Dungeon

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#143]
Task name: Red Dragons in Myths' Guild Dungeon
    Npc Name: Red dragon
    Npc Location(Tile):  Also Safespot tile
    Safespot?: Yes.

![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/bac16726-05a4-42bd-8bca-a4e387684cee)

    Prayer recommended: No
    Antipoison/Antifire: Antifire Shield
    Slayer Gear/Additional requirements: Dragon slayer 2
    Closest bank: Myths guild bank

**Comment by PTYB** [comment]
Will be added in next release

**Comment by PTYB** [comment]
Closing cuz no complaint
