### ISSUE TITLE
[Enhancement] Trollheim teleport support for getting to GWD, Potentially a teleport to task option?

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#144]
will also add that it gets to GWD after manually teleporting to trollheim, bloodvelds work great. I also had the runes required for trollheim with me when it was trying to figure out how to get there.

**Comment by PTYB** [comment]
If you have it in inventory it will use it

**Comment by Rallik-Pog** [comment]
Got it, I had the runes with me. Maybe it was because dax was down.
