### ISSUE TITLE
Suggestion: update Black Demons Safespot at Chasm of Fire

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#147]
Heres the tile, better spot than the current one.

![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/6f156626-65c5-46a3-913e-92794827dc34)

Video: https://youtu.be/QyUYkXC--qU?si=Xg2ECMs3rPK8mL5Z&t=164

**Comment by PTYB** [comment]
Seems better, will try checkout this week

**Comment by PTYB** [comment]
Released in latest
