### ISSUE TITLE
[Enhancement] House Jewellery Box Support

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#149]
https://oldschool.runescape.wiki/w/Jewellery_box_space
[n](https://oldschool.runescape.wiki/w/Ornate_jewellery_box)
https://oldschool.runescape.wiki/w/Fancy_jewellery_box
https://oldschool.runescape.wiki/w/Basic_jewellery_box

Close if this is posted elsewhere, I was unable to find it from searching.

**Comment by PTYB** [comment]
Will be released soon

**Comment by PTYB** [comment]
Released
