### ISSUE TITLE
Character stuck with Black Demon Task + Cannon Utilization

### ISSUE THREAD

**Issue by iamharmor** [PTYB/SlayerIssueTracker#152]
Happens on this tile every time, i've encountered my character dying 5-10 times, twice yesterday and I was fortunate to catch it today, this seems to happen when you initially run to this task and place a cannon your character remains sitting by the cannon stuck, was getting wacked to death by a black demon while my character didnt respond, as i moved my character to the left it proceeded to register the safe tile and utilize it, but something initially makes it go wonky. tried to grab logs but this thing wont paste ahhh

Slayer Master: Nieve
Task: Black Demons
Hotel: Trivago
ID: eca0a811-28b3-44a4-aa8d-9cfa3cb9b787
Gear: https://gyazo.com/579ac52f0102960731f792381fa45a09
Task Setup: https://gyazo.com/6593be4adbc657bf3516770bd35c4937

Dies on this exact tile every time: https://gyazo.com/7912e2269c78dda554847bc2db364abf
i tried to grab logs : ( https://gyazo.com/e0a11b41136f50b6980fef6263312f55

**Comment by iamharmor** [comment]
got another task there, it lost the cannon, has happened multiple times, something with the cannon interaction
https://gyazo.com/bdfc377d335c5e01e766fb279be18cc0

**Comment by PTYB** [comment]
Need actual logs sorry
