### ISSUE TITLE
[Enhancement] Stop script when getting specific task.

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#155]
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/6c1ea0c6-bc98-42ac-9d25-0892c30f3137)
Something like this so if its a alternative to a boss, for example blue dragons = vorkath alternative. So we can do the boss alternative ourselves or use other scripts/means.

**Comment by PTYB** [comment]
This has been released
