### ISSUE TITLE
Add Masori (f) as a gear option

### ISSUE THREAD

**Issue by meatFlaps** [PTYB/SlayerIssueTracker#156]
Masori is an option for gear, but Masori (f) is not

**Comment by PTYB** [comment]
Can you send me ID's/exact names and I can add them

**Comment by meatFlaps** [comment]
> Can you send me ID's/exact names and I can add them

Masori mask (f) 27235
Masori body (f) 27238
Masori chaps (f) 27241
![image](https://github.com/PTYB/SlayerIssueTracker/assets/141674971/d50d5a48-7651-4986-94fa-142dc9517f10)

**Comment by PTYB** [comment]
Will be released in a few minutes
