### ISSUE TITLE
POH Salve GY portal not showing up in task config

### ISSUE THREAD

**Issue by adjustabundant** [PTYB/SlayerIssueTracker#164]
**Issue:** House config supports Salve GY portal, but it can't be selected in the House to task/bank config options for each task
**Current behavior:** Other portals can be selected, but not Salve GY
**Expected behavior:** Would like to force the script to tele to house, take Salve GY portal, then walk to task/bank (using fairy rings)
**Screenshots/Video:** 
![salvegy2](https://github.com/PTYB/SlayerIssueTracker/assets/152431223/77b3bf10-9a03-4b10-a60d-c8ac2005fdfd)
![salvegy1](https://github.com/PTYB/SlayerIssueTracker/assets/152431223/47b23d7b-24e8-406b-9f99-c803fe223721)
**Master:** Nieve
**Task:** Multiple (Wyrms, for example)
**Additional information:**

**Comment by PTYB** [comment]
Will be released soon

**Comment by PTYB** [comment]
Released
