### ISSUE TITLE
[Enhancement] POH Spirit Tree support

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#167]
Couple of different versions, there's the spirit tree & then the fairy ring + spirit tree.

I know you are aware of this enhancement, I didn't see it in the issues. Feel free to delete if you want.

**Comment by PTYB** [comment]
Planned for this week

**Comment by PTYB** [comment]
Released now

**Comment by PTYB** [comment]
Added
