### ISSUE TITLE
Wyrm - Safespotting issue

### ISSUE THREAD

**Issue by Jason-9494** [PTYB/SlayerIssueTracker#170]
**Issue:**
- Very "bot-like" for safe-spotting

**Current behavior:**
- Consistently trying to click on the same safe-spot slot and hitting Wyrm, so its running back and forth back and forth

**Expected behavior:**
- From what I see, I think safe spot area can be slightly adjusted a little, to be slightly outside of current spot.

**Screenshots/Video:**
**Master:**
- Nieve

**Task:**
- Wyrm

**Additional information:**

**Comment by PTYB** [comment]
Needs long range. I don't like to activate as it could give pures defense experience.

**Comment by PTYB** [comment]
Need pictures to understand what your talking about?

**Comment by PTYB** [comment]
Assume you were meaning this, https://github.com/PTYB/SlayerIssueTracker/issues/194

Will close this and you can track the above.
