### ISSUE TITLE
[Bug] Elidinis ward item id

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#172]
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/a215967f-61fe-436c-86c1-5424576afe6d)
unable to find Elidinis ward when in inventory/equiped.

**Comment by PTYB** [comment]
Will be fixed next release, you will need to re-add them

**Comment by PTYB** [comment]
Forgot to say this is deployed
