### ISSUE TITLE
[Nieve][Mutated Zygomites] Not walking to task

### ISSUE THREAD

**Issue by Jason-9494** [PTYB/SlayerIssueTracker#177]
**Issue:**
**Current behavior:**
- After banking, status is walking to area but it just didn't move at all
**Expected behavior:**
- Should walk to task
**Screenshots/Video:**
**Master:**
- Nieve
**Task:**
- Mutated zygomites
**Logs:**
**Additional information:**
- I also tried moving manually to zanaris, but it still wants to go bank and will continue to stuck there

**Comment by PTYB** [comment]
Do you have a dramen staff?
