### ISSUE TITLE
cant get the config page to load

### ISSUE THREAD

**Issue by kneegr** [PTYB/SlayerIssueTracker#18]
Issue: config page not loading on site
Current behavior: i open the site and every other link is clickable and does something except the config page, i click that and its just a spinning circle 
Expected behavior: ive never used it before so i dont know the expected behavior 
Screenshots/Video:![image](https://user-images.githubusercontent.com/127032135/222965992-9c5299cc-6579-47c2-ba8d-42f0b18ac7b7.png)
![image](https://user-images.githubusercontent.com/127032135/222966007-0de5c355-c217-48cc-840e-cf73e71b2941.png)
Additional information:

@PTYB i think im one of the people with beta access? but on the usefull links theres a configuration website, i go to that, login wiht my google acc, the configuration list page shows up, where you can put in a name and submit, i selected konar, named it "new 1" to test, then hit submit, it brings me to a page with a sidebar, that has all the selections, list page, config page, gear, ect.., on the configuration page it just has a loading circle, i click list page it takes me back to the list page, i reclick the test one i made and it takes meback to the spinning circle, the gear and monsters tabs all seem to be functioning correctly, i have a gearset for mele and ranged already and i can click a mon on the list and it populates the gear and items, 

 the pics should show the circle thats loading, and the other should show it does populate the gear from the gear tabs, when i opened the script on my phone it said to input the config id, i dont see anywhere on the site to get the id, unless its on that config page that just sits and loads
sorry i dont know how to write these posts first time on github

**Comment by PTYB** [comment]
I just tested it on my local and its not forever loading.
The configuration page indeed does show the ID although you can grab it from the url

> http://45.79.80.90/**838d5d47-9511-43e3-9151-4a8c7af2dcfa**/configuration

**Comment by PTYB** [comment]
Could you please inspect element and grab me console logs?

Inspect element -> Console logs

**Comment by Robsukka** [comment]
Same issue here, Console logs: 

Loading initial page
:3333/api/slayer/configuration/f5d4d49f-6f0e-4f3f-b684-98dd8326a9fe:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)
main.0afe51794d47816a.js:75 error message:  401
:3333/api/slayer/configuration/f5d4d49f-6f0e-4f3f-b684-98dd8326a9fe:1          Failed to load resource: the server responded with a status of 401 (Unauthorized)
main.0afe51794d47816a.js:75 error message:  401
main.0afe51794d47816a.js:102 Loading initial page
:3333/api/slayer/configuration/f5d4d49f-6f0e-4f3f-b684-98dd8326a9fe:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
main.0afe51794d47816a.js:75 error message:  403
main.0afe51794d47816a.js:102 Loading configuration false
:3333/api/slayer/configuration/f5d4d49f-6f0e-4f3f-b684-98dd8326a9fe:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
main.0afe51794d47816a.js:75 error message:  403
:3333/api/slayer/configuration/f5d4d49f-6f0e-4f3f-b684-98dd8326a9fe:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
main.0afe51794d47816a.js:75 error message:  403
:3333/api/slayer/configuration/f5d4d49f-6f0e-4f3f-b684-98dd8326a9fe:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
main.0afe51794d47816a.js:75 error message:  403
:3333/api/slayer/configuration/f5d4d49f-6f0e-4f3f-b684-98dd8326a9fe:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
main.0afe51794d47816a.js:75 error message:  403
:3333/api/slayer/configuration/f5d4d49f-6f0e-4f3f-b684-98dd8326a9fe:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
main.0afe51794d47816a.js:75 error message:  403
:3333/api/slayer/configuration/f5d4d49f-6f0e-4f3f-b684-98dd8326a9fe:1          Failed to load resource: the server responded with a status of 403 (Forbidden)
main.0afe51794d47816a.js:75 error message:  403
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND

**Comment by PTYB** [comment]
Should be resolved now, could you please give it another go @Robsukka  and @kneegr

**Comment by Robsukka** [comment]
Its working now, thank you. @PTYB
