### ISSUE TITLE
Add construction cape to Poh

### ISSUE THREAD

**Issue by SlipperyPickle** [PTYB/SlayerIssueTracker#183]
**Issue:** Is it possible to have the construction cape added to teleport to poh?
**Current behavior:** Not supported
**Expected behavior:** -
**Screenshots/Video:** -
**Master:** -
**Task:** -
**Logs:** not needed.
**Additional information:** -

**Comment by PTYB** [comment]
Need item names etc

**Comment by iamharmor** [comment]
pm'ed item names

**Comment by SlipperyPickle** [comment]
Construct. cape -> 9789
Construct. cape(t) -> 9790

**Comment by PTYB** [comment]
Forgot to mention this should be released.

**Comment by SlipperyPickle** [comment]
Works!
