### ISSUE TITLE
Suqah cannon tile incorrect

### ISSUE THREAD

**Issue by SlipperyPickle** [PTYB/SlayerIssueTracker#184]
**Issue:** The cannon tile for Suqah is incorrect
**Current behavior:** Tries to walk to incorrect tile, which isn't reachable. 
**Expected behavior:** Walk to a correct tile.
**Screenshots/Video:** -
**Master:** - 
**Task:** -
**Logs:** ```12-22 17:00:51.140  3627  4614 I com.pty.slayer.logic.killing.leafs.cannon.WalkToCannonTile:  [pool-32-thread-1] 12-22 17:00:51.140  INFO c.p.s.l.k.l.c.WalkToCannonTile - Walking to cannontile Tile(x=2041, y=3865, floor=0, localX=-15, localY=1)```
**Additional information:**

**Comment by PTYB** [comment]
Was given that tile I believe, what is a good one?

**Comment by SlipperyPickle** [comment]
```Tile(2109, 3942, 0)```

**Comment by PTYB** [comment]
Will be updated next release

**Comment by SlipperyPickle** [comment]
Works!
