### ISSUE TITLE
Add a check for run energy at lizardman shamans

### ISSUE THREAD

**Issue by emthenem** [PTYB/SlayerIssueTracker#185]
**Issue:** Most of the times when I get to the area Molch lizardman it doesnt have any run energy left and it doesnt turn the run back on so it walks while fighting the shamans
**Current behavior:** Doesnt turn run back on
**Expected behavior:** A check for run energy
**Screenshots/Video:**
**Master:** Nieve
**Task:** Lizardman shaman
**Logs:**
**Additional information:**

**Comment by PTYB** [comment]
What does a check for run energy mean? Wait till certain amount etc

**Comment by emthenem** [comment]
> What does a check for run energy mean? Wait till certain amount etc

Ye, maybe something like turn on run energy when its at 20% or something would be nice. Because I noticed it was walking while having 100% run energy.

**Comment by PTYB** [comment]
Fix will be released tomorrow

**Comment by PTYB** [comment]
Released
