### ISSUE TITLE
[Enhancement] Basilisk Knights Slayer Task

### ISSUE THREAD

**Issue by iamharmor** [PTYB/SlayerIssueTracker#186]
**Request:** Ability to choose Isle of Stone with basilisk knights as an option for task when assigned Basilisks.
**Current behavior:** Fights Basilisks in Fremmenik Dungeon.
**Expected behavior:** Offers choice to fight Basilisk Knights.
**Additional information:** This task is assignable by Duradel, Nieve, aswell as Konar. This task drops an item at a 1/1000 drop rate when on task for second highest of any helmet behind the torva full helm. Iron man friendly, off task farming not the worst 1/5000 off task.

Requirements:
60+ Slayer and Fremmenik Exiles
https://oldschool.runescape.wiki/w/Basilisk_Knight

**Comment by PTYB** [comment]
I will add this to my quest backlog

**Comment by PTYB** [comment]
Closed due to better report - https://github.com/PTYB/SlayerIssueTracker/issues/204
