### ISSUE TITLE
Lizardman shaman doesn't switch back to crossbow from dramen staff

### ISSUE THREAD

**Issue by adjustabundant** [PTYB/SlayerIssueTracker#188]
**Issue:** lizardman shaman script uses dramen staff to return to caves but it immediately keeps trying to melee the shaman with the dramen staff instead of reswitching back to the crossbow. Came back to a death but now I know why, just re ran the script to see it again, seems to work fine after manually switching back to crossbow
**Current behavior:** melee them with dramen stafd
**Expected behavior:** equip rune crossbow to range shamen
**Screenshots/Video:**
**Master:**
**Task:**
**Logs:**
**Additional information:**

**Comment by PTYB** [comment]
Fix will be released tomorrow after some testing.

**Comment by PTYB** [comment]
Released
