### ISSUE TITLE
not starting up after config

### ISSUE THREAD

**Issue by kneegr** [PTYB/SlayerIssueTracker#19]
@PTYB  Issue: cant get the script to run after inputting my config id
Current behavior: when starting  the script with my config id it closes the script nothing happens
Expected behavior: for it to run? idk what its supposed to do after you hit start script anbd put in your config id i dont know if there are any options to select or anything
Screenshots/Video:
Additional information: i attached the logs that i got from pow when starting the script 
[dump.txt](https://github.com/PTYB/SlayerIssueTracker/files/10892895/dump.txt)

**Comment by PTYB** [comment]
Should be resolved now
