### ISSUE TITLE
suggestion: baby black dragons on task for black dragons

### ISSUE THREAD

**Issue by adjustabundant** [PTYB/SlayerIssueTracker#191]
Not an issue just a suggestion to include baby black dragons as quick option for this specific task, run past them on way to adults

**Current behavior:** attacks adult black dragons
**Expected behavior:** would love if we could select to knock out task quick with the 3 baby black dragons on way to taverly slayer task
**Screenshots/Video:**
**Master:** nieve
**Task:** black dragons
**Logs:**
**Additional information:**

**Comment by PTYB** [comment]
Which specific location?

**Comment by PTYB** [comment]
Which default style do you think would be best?

**Comment by adjustabundant** [comment]
I think range works just fine since it's default for adult black drags in same path

**Comment by PTYB** [comment]
Theres no extra effort for melee/ranged setting

**Comment by PTYB** [comment]
Added
