### ISSUE TITLE
[Bug] Black Dragons at Myths Guild

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#193]
**Issue:** Script stops when on task.
**Current behavior:** Script auto stops.
**Expected behavior:** Goes to myths guild and kills black dragons
**Screenshots/Video:**
**Master:** Konar
**Task:** Black Dragons at Myths Guild 
**Logs:** 16:33:06.823  INFO o.p.a.s.o.ScriptConfigurationOption$Companion - Set field data to
12-29 16:33:06.823  4151  4151 I com.pty.slayer.Slayer:  [main] 12-29 16:33:06.823  INFO c.p.s.Slayer - Field not found! Auto execute gargoyle
12-29 16:33:06.937     0     0 W atkbd serio2: Unknown key released (translated set 2, code 0x0 on bstkbd).
12-29 16:33:06.937     0     0 W atkbd serio2: Use 'setkeycodes 00 <keycode>' to make it known.
12-29 16:33:06.951     0     0 W atkbd serio2: Unknown key released (translated set 2, code 0x0 on bstkbd).
12-29 16:33:06.951     0     0 W atkbd serio2: Use 'setkeycodes 00 <keycode>' to make it known.
12-29 16:33:06.966     0     0 W atkbd serio2: Unknown key released (translated set 2, code 0x0 on bstkbd).
12-29 16:33:06.966     0     0 W atkbd serio2: Use 'setkeycodes 00 <keycode>' to make it known.
12-29 16:33:06.973     0     0 D logd    : logdr: UID=2000 GID=2000 PID=6575 n tail=0 logMask=99 pid=0 start=0ns timeout=0ns
12-29 16:33:06.980     0     0 W atkbd serio2: Unknown key released (translated set 2, code 0x0 on bstkbd).
12-29 16:33:06.980     0     0 W atkbd serio2: Use 'setkeycodes 00 <keycode>' to make it known.
12-29 16:33:06.998     0     0 W atkbd serio2: Unknown key released (translated set 2, code 0x0 on bstkbd).
12-29 16:33:06.998     0     0 W atkbd serio2: Use 'setkeycodes 00 <keycode>' to make it known.
12-29 16:33:07.020     0     0 W atkbd serio2: Unknown key released (translated set 2, code 0x0 on bstkbd).
12-29 16:33:07.020     0     0 W atkbd serio2: Use 'setkeycodes 00 <keycode>' to make it known.
12-29 16:33:07.229     0     0 D logd    : logdr: UID=2000 GID=2000 PID=6579 n tail=0 logMask=99 pid=0 start=0ns timeout=0ns
12-29 16:33:07.473     0     0 D logd    : logdr: UID=2000 GID=2000 PID=6582 n tail=0 logMask=99 pid=0 start=0ns timeout=0ns
12-29 16:33:07.722     0     0 D logd    : logdr: UID=2000 GID=2000 PID=6585 n tail=0 logMask=99 pid=0 start=0ns timeout=0ns
12-29 16:33:07.950  1840  2858 W APM::AudioPolicyEngine: getDevicesForStrategy() unknown strategy: -1
12-29 16:33:07.955  4151  4151 I com.pty.slayer.Slayer:  [main] 12-29 16:33:07.954  INFO c.p.s.Slayer - Starting Script with JSON: [{"allowedValues":[],"defaultValue":"","description":"The configuration ID from the website.","enabled":true,"name":"Configuration","optionType":"STRING","value":"86683f33-469b-47c1-b784-7254ead2695a","visible":true},{"allowedValues":[],"defaultValue":"","description":"(Optional)The task npc you want to farm(Must match task exactly)","enabled":true,"name":"Specify Npc","optionType":"STRING","value":"","visible":true},{"allowedValues":[],"defaultValue":"","description":"(Optional)The location you want to farm(Only Konar, must match exactly)","enabled":true,"name":"Specify Location","optionType":"STRING","value":"","visible":true},{"allowedValues":[],"defaultValue":true,"description":"Do you have auto execute gargoyle bought?","enabled":true,"name":"Auto execute gargoyle","optionType":"BOOLEAN","value":true,"visible":true}]
12-29 16:33:07.955  2033  4546 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
12-29 16:33:07.955  4151  6544 I FlagManager:  [pool-27-thread-1] 12-29 16:33:07.955  INFO FlagManager - Updating key current_script to value [Private] PTY Slayer
12-29 16:33:07.973  2033  4546 D WindowManager: bstSendTopDisplayedOnFocusChange packageName : com.jagex.oldscape.android  activityName : com.jagex.android.MainActivity  mouseAction  :   lastSentMouseAction :
12-29 16:33:07.985  4151  4269 I DeviceInfo: logging to crashlytics [Added flags FOCUSED (0x02) -> RESUMED | FOCUSED | STARTED | WINDOWCREATED | SURFACECREATED (0x1F)]
12-29 16:33:07.985  4151  4269 I DeviceInfo: set custom key [STATE_LAST_APP_STATE], value=[RESUMED | FOCUSED | STARTED | WINDOWCREATED | SURFACECREATED]
12-29 16:33:07.985  2033  4546 D InputMethodManagerService: packageName=com.jagex.oldscape.android, activityName=com.jagex.android.MainActivity
12-29 16:33:07.985  2033  4546 D InputMethodManagerService: ime_enabled = false is same as last value, no change
12-29 16:33:08.011  4151  6544 I com.pty.slayer.Slayer:  [pool-27-thread-1] 12-29 16:33:08.010  INFO c.p.s.Slayer - Debug: null | null
12-29 16:33:08.011  4151  6544 I com.pty.slayer.Slayer:  [pool-27-thread-1] 12-29 16:33:08.011  INFO c.p.s.Slayer - Auto execute gargoyle true
12-29 16:33:08.026  4151  6544 I com.pty.slayer.services.TaskService:  [pool-27-thread-1] 12-29 16:33:08.025  INFO c.p.s.s.TaskService - Calling: http://45.79.80.90:3333/api/powbot/slayer/config/86683f33-469b-47c1-b784-7254ead2695a/master
12-29 16:33:08.060  4151  6544 I FlagManager:  [pool-27-thread-1] 12-29 16:33:08.060  INFO FlagManager - Updating key script_state to value Running
12-29 16:33:08.110  4151  6544 I com.pty.slayer.Slayer:  [pool-27-thread-1] 12-29 16:33:08.110  INFO c.p.s.Slayer - Tree Execution line: Init?[S] -> Knows task?[S] -> Knows task?[F] -> Can check task?[S] -> Widget open?[F] -> Has slayer checking item?[S] -> Check slayer task
12-29 16:33:08.165  1840  1994 W APM::AudioPolicyEngine: getDevicesForStrategy() unknown strategy: -1
12-29 16:33:08.165  2033  2626 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
12-29 16:33:08.178  4151  6544 I Menu    :  [pool-27-thread-1] 12-29 16:33:08.178  INFO Menu - trying to click menu itemorg.powbot.api.rt4.Menu$TextFilter@916a273
12-29 16:33:07.972     0     0 D logd    : logdr: UID=2000 GID=2000 PID=6588 n tail=0 logMask=99 pid=0 start=0ns timeout=0ns
12-29 16:33:08.200  4151  6544 I System.out: WANT (check slayer helmet (i))
12-29 16:33:08.201  4151  6544 I System.out: WANT (check slayer helmet (i))
12-29 16:33:08.201  4151  6544 I Menu    :  [pool-27-thread-1] 12-29 16:33:08.201  INFO Menu - found menu item at 1
12-29 16:33:08.344  4151  6544 I org.powbot.api.waiter.ActionWaiter:  [pool-27-thread-1] 12-29 16:33:08.344  INFO o.p.a.w.ActionWaiter - action waiter finished after 0
12-29 16:33:08.226     0     0 D logd    : logdr: UID=2000 GID=2000 PID=6591 n tail=0 logMask=99 pid=0 start=0ns timeout=0ns
12-29 16:33:08.473     0     0 D logd    : logdr: UID=2000 GID=2000 PID=6594 n tail=0 logMask=99 pid=0 start=0ns timeout=0ns
12-29 16:33:08.832  4151  5233 I com.pty.slayer.Slayer:  [pool-17-thread-1] 12-29 16:33:08.832  INFO c.p.s.Slayer - Message: <col=ef1020>You're assigned to kill </col>black dragons in the Myths' Guild Dungeon<col=ef1020>; only </col>48<col=ef1020> more to go.
12-29 16:33:08.833  4151  5233 I com.pty.slayer.Slayer:  [pool-17-thread-1] 12-29 16:33:08.833  INFO c.p.s.Slayer - Message: <col=ef1020>You've completed </col>258 tasks <col=ef1020>in a row and currently have a total of </col>2,118 points<col=ef1020>.
12-29 16:33:08.877  4151  6544 I com.pty.slayer.logic.init.leafs.CheckSlayerTask:  [pool-27-thread-1] 12-29 16:33:08.876  INFO c.p.s.l.i.l.CheckSlayerTask - Slayer widget open true
12-29 16:33:08.723     0     0 D logd    : logdr: UID=2000 GID=2000 PID=6597 n tail=0 logMask=99 pid=0 start=0ns timeout=0ns
12-29 16:33:09.066  4151  6544 I com.pty.slayer.Slayer:  [pool-27-thread-1] 12-29 16:33:09.065  INFO c.p.s.Slayer - Tree Execution line: Init?[S] -> Knows task?[S] -> Knows task?[F] -> Can check task?[S] -> Widget open?[S] -> Slayer widget
12-29 16:33:09.067  4151  6544 I com.pty.slayer.services.TaskService:  [pool-27-thread-1] 12-29 16:33:09.066  INFO c.p.s.s.TaskService - Calling: http://45.79.80.90:3333/api/powbot/slayer/configuration/86683f33-469b-47c1-b784-7254ead2695a/location/Myths'%20Guild%20Dungeon/task/Black%20Dragons
12-29 16:33:09.118  4151  6544 I com.pty.slayer.logic.helpers.WidgetHelper:  [pool-27-thread-1] 12-29 16:33:09.118  INFO c.p.s.l.h.WidgetHelper - Received task: Black Dragons
12-29 16:33:09.122  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.122  INFO c.p.s.m.MapToTask - Mapping local user configuration Use cannon 0
12-29 16:33:09.122  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.122  INFO c.p.s.m.MapToTask - Action: null
12-29 16:33:09.122  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.122  INFO c.p.s.m.MapToTask - Items to Alch: 189 | Items to ignore: 200 | Bury bones: true | Food to eat: Shark
12-29 16:33:09.123  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.122  INFO c.p.s.m.MapToTask - Cannon tile null, null, null
12-29 16:33:09.123  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.123  INFO c.p.s.m.MapToTask - Loot values: Individual: 600 | 100
12-29 16:33:09.123  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.123  INFO c.p.s.m.MapToTask - Has regions? : false
12-29 16:33:09.123  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.123  INFO c.p.s.m.MapToTask - Mapping equipped gear setup
12-29 16:33:09.123  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.123  INFO c.p.s.m.MapToTask - Mapping equipped item requirements
12-29 16:33:09.123  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.123  INFO c.p.s.m.MapToTask - Mapping gear slot HEAD
12-29 16:33:09.123  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.123  INFO c.p.s.m.MapToTask - Mapping equipped item requirements
12-29 16:33:09.124  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.124  INFO c.p.s.m.MapToTask - Mapping gear slot TORSO
12-29 16:33:09.124  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.124  INFO c.p.s.m.MapToTask - Mapping equipped item requirements
12-29 16:33:09.124  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.124  INFO c.p.s.m.MapToTask - Mapping gear slot LEGS
12-29 16:33:09.124  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.124  INFO c.p.s.m.MapToTask - Mapping equipped item requirements
12-29 16:33:09.124  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.124  INFO c.p.s.m.MapToTask - Mapping gear slot CAPE
12-29 16:33:09.124  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.124  INFO c.p.s.m.MapToTask - Mapping equipped item requirements
12-29 16:33:09.124  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.124  INFO c.p.s.m.MapToTask - Mapping gear slot NECK
12-29 16:33:09.124  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.124  INFO c.p.s.m.MapToTask - Mapping equipped item requirements
12-29 16:33:09.124  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.124  INFO c.p.s.m.MapToTask - Mapping gear slot MAIN_HAND
12-29 16:33:09.124  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.124  INFO c.p.s.m.MapToTask - Mapping equipped item requirements
12-29 16:33:09.124  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.124  INFO c.p.s.m.MapToTask - Mapping gear slot OFF_HAND
12-29 16:33:09.125  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.125  INFO c.p.s.m.MapToTask - Mapping equipped item requirements
12-29 16:33:09.125  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.125  INFO c.p.s.m.MapToTask - Mapping gear slot HANDS
12-29 16:33:09.125  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.125  INFO c.p.s.m.MapToTask - Mapping equipped item requirements
12-29 16:33:09.125  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.125  INFO c.p.s.m.MapToTask - Mapping gear slot FEET
12-29 16:33:09.125  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.125  INFO c.p.s.m.MapToTask - Mapping equipped item requirements
12-29 16:33:09.125  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.125  INFO c.p.s.m.MapToTask - Mapping gear slot RING
12-29 16:33:09.125  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.125  INFO c.p.s.m.MapToTask - Mapping equipped item requirements
12-29 16:33:09.126  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.125  INFO c.p.s.m.MapToTask - Mapping gear slot QUIVER
12-29 16:33:09.126  4151  6544 I com.pty.slayer.mappers.MapToTask:  [pool-27-thread-1] 12-29 16:33:09.126  INFO c.p.s.m.MapToTask - Getting npc Black Dragon
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager:  [pool-27-thread-1] 12-29 16:33:09.139 ERROR o.p.m.s.ScriptManager - script poll failed ([Private] PTY Slayer)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager:  [pool-27-thread-1] 12-29 16:33:09.140 ERROR o.p.m.s.ScriptManager - java.util.NoSuchElementException: Array contains no element matching the predicate.
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at com.pty.slayer.mappers.MapToTask.getNpc(MapToTask.kt:243)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at com.pty.slayer.mappers.MapToTask.mapResponseToTask(MapToTask.kt:52)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at com.pty.slayer.logic.helpers.WidgetHelper.getSlayerTaskFromWidget(WidgetHelper.kt:69)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at com.pty.slayer.WidgetOpen$successComponent$1.invoke(StartingBranches.kt:69)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at com.pty.slayer.WidgetOpen$successComponent$1.invoke(StartingBranches.kt:65)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.api.script.tree.SimpleLeaf.execute(Leaf.kt:13)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.api.script.tree.TreeScript.poll(TreeScript.kt:19)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.mobile.script.ScriptManager$runScript$3.invokeSuspend(ScriptManager.kt:506)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.mobile.script.ScriptManager$runScript$3.invoke(Unknown Source:8)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.mobile.script.ScriptManager$runScript$3.invoke(Unknown Source:4)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.mobile.script.ScriptManager.runScript(ScriptManager.kt:504)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.mobile.script.ScriptManager.access$runScript(ScriptManager.kt:49)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at org.powbot.mobile.script.ScriptManager$start$3.invokeSuspend(ScriptManager.kt:232)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager: 	at java.lang.Thread.run(Thread.java:923)
12-29 16:33:09.140  4151  6544 E org.powbot.mobile.script.ScriptManager:
12-29 16:33:09.140  4151  6544 W System.err: java.util.NoSuchElementException: Array contains no element matching the predicate.
12-29 16:33:09.140  4151  6544 W System.err: 	at com.pty.slayer.mappers.MapToTask.getNpc(MapToTask.kt:243)
12-29 16:33:09.140  4151  6544 W System.err: 	at com.pty.slayer.mappers.MapToTask.mapResponseToTask(MapToTask.kt:52)
12-29 16:33:09.140  4151  6544 W System.err: 	at com.pty.slayer.logic.helpers.WidgetHelper.getSlayerTaskFromWidget(WidgetHelper.kt:69)
12-29 16:33:09.140  4151  6544 W System.err: 	at com.pty.slayer.WidgetOpen$successComponent$1.invoke(StartingBranches.kt:69)
12-29 16:33:09.140  4151  6544 W System.err: 	at com.pty.slayer.WidgetOpen$successComponent$1.invoke(StartingBranches.kt:65)
12-29 16:33:09.140  4151  6544 W System.err: 	at org.powbot.api.script.tree.SimpleLeaf.execute(Leaf.kt:13)
12-29 16:33:09.140  4151  6544 W System.err: 	at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-29 16:33:09.140  4151  6544 W System.err: 	at org.powbot.api.script.tree.Branch.execute(Branch.kt:38)
12-29 16:33:09.140  4151  6544 W System.err: 	at org.powbot.api.script.tree.TreeScript.poll(TreeScript.kt:19)
12-29 16:33:09.140  4151  6544 W System.err: 	at org.powbot.mobile.script.ScriptManager$runScript$3.invokeSuspend(ScriptManager.kt:506)
12-29 16:33:09.140  4151  6544 W System.err: 	at org.powbot.mobile.script.ScriptManager$runScript$3.invoke(Unknown Source:8)
12-29 16:33:09.140  4151  6544 W System.err: 	at org.powbot.mobile.script.ScriptManager$runScript$3.invoke(Unknown Source:4)
12-29 16:33:09.140  4151  6544 W System.err: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
12-29 16:33:09.140  4151  6544 W System.err: 	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
12-29 16:33:09.140  4151  6544 W System.err: 	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
12-29 16:33:09.140  4151  6544 W System.err: 	at org.powbot.mobile.script.ScriptManager.runScript(ScriptManager.kt:504)
12-29 16:33:09.140  4151  6544 W System.err: 	at org.powbot.mobile.script.ScriptManager.access$runScript(ScriptManager.kt:49)
12-29 16:33:09.140  4151  6544 W System.err: 	at org.powbot.mobile.script.ScriptManager$start$3.invokeSuspend(ScriptManager.kt:232)
12-29 16:33:09.140  4151  6544 W System.err: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-29 16:33:09.140  4151  6544 W System.err: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-29 16:33:09.140  4151  6544 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-29 16:33:09.140  4151  6544 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-29 16:33:09.140  4151  6544 W System.err: 	at java.lang.Thread.run(Thread.java:923)
12-29 16:33:09.140  4151  6544 I FlagManager:  [pool-27-thread-1] 12-29 16:33:09.140  INFO FlagManager - Updating key current_script to value
12-29 16:33:09.146  4151  6544 I FlagManager:  [pool-27-thread-1] 12-29 16:33:09.146  INFO FlagManager - Updating key script_state to value Stopped
.593  5071  5116 I NearbyConnections: Client 0p:com.google.android.gms.nearby.sharing disconnecting
12-29 16:33:16.593  5071  5116 I Nearby  : (REDACTED) Successfully shutdown executor %s.
12-29 16:33:16.593  5071  5191 I NearbyConnections: Because they unbound from our service, all state for client 184180816 will now be cleaned up.
12-29 16:33:16.594  5071  5191 I Nearby  : (REDACTED) Successfully shutdown executor %s.
12-29 16:33:16.600  5071  5191 I Nearby  : (REDACTED) Successfully shutdown executor %s.
12-29 16:33:16.600  5071  5191 I NearbyConnections: Generated local endpoint id 3R9N for client 184180816
12-29 16:33:16.600  5071  5191 I Nearby  : (REDACTED) Successfully shutdown executor %s.
12-29 16:33:16.602  5071  5191 I Nearby  : (REDACTED) Successfully shutdown executor %s.

**Additional information:**

**Comment by PTYB** [comment]
Will be fixed next release

**Comment by PTYB** [comment]
Released
