### ISSUE TITLE
Improvement for Wyrms task safespot

### ISSUE THREAD

**Issue by Laddad123** [PTYB/SlayerIssueTracker#194]
**Issue: I guess not really an issue, but it doesnt need long range, I discovered this when doing some manual work. 
**Current behavior:** Goes to the furthest tile away and needs long-range to hit the wyrm
**Expected behavior:** Move 1 step forward and use Rapid/Accurate instead
**Screenshots/Video:** 
https://streamable.com/tn5aem

**Master:** Konar
**Task:** Wyrms
**Logs:** ---
**Additional information:** Video says most of it, got locations on, if you need naything more lemme know

**Comment by PTYB** [comment]
Thanks for the video, will be fixed in next release

**Comment by PTYB** [comment]
Released
