### ISSUE TITLE
Add Jormungand's Prison location related tasks

### ISSUE THREAD

**Issue by meatFlaps** [PTYB/SlayerIssueTracker#195]
Jormungand's Prison on Island of Stone appears to not be currently supported, I've received a Dagannoth task here and it seems like a pretty straight forward addition. Task was recieved from Konar, you just travel from Haskell on the western-most dock in Relleka to the Island of Stone and then enter the dungeon. There is 3 areas with Dagannoth's within the dungeon

**Comment by PTYB** [comment]
Need tiles location quest requirements etc. Also a screenshot of the widget showing the exact task location etc
