### ISSUE TITLE
Refuses to pick up certain stacked items

### ISSUE THREAD

**Issue by meatFlaps** [PTYB/SlayerIssueTracker#199]
For example it will not pick up Chaos Runes or Fire Runes, no matter how many there are. I've adjusted the minimum stack size multiple times and it still for whatever reason won't pick them up. It also does this for coins, some slayer monsters drop 3k+ stacks of coins and the script will not pick them up

Issue: it will not pick up certain items even when the stack size is above threshold entered in settings
Current behavior: it is not picking up certain items even when the stack size is above threshold entered in settings
Expected behavior: it should be picking up items above the threshold entered in settings
Screenshots/Video: i didn't get any as i figured they weren't really needed, i'll get some next time i use the script but it won't be for awhile
Master: Konar
Task: Multiple
Additional information:

**Comment by PTYB** [comment]
Use template and need logs

**Comment by meatFlaps** [comment]
> Use template and need logs

all the information you ask for in the template is in the original post minus the master was Konar, which doesn't really matter since the items dropped aren't dependent on the master
i'll rewrite it in your format regardless, but just so we're clear what do you want for logs? wouldn't there be nothing in the logs related to it not picking the items up? or does the logs include every single dropped item by every single NPC?

**Comment by PTYB** [comment]
There are logs which show why it ignores items. Also there is no stack size option, there is only a stack value option.

EG

Ignoring fire rune because 100gp is below stack loot value 1000

**Comment by meatFlaps** [comment]
> There are logs which show why it ignores items. Also there is no stack size option, there is only a stack value option.
> 
> EG
> 
> Ignoring fire rune because 100gp is below stack loot value 1000

you knew what i meant clearly lol

**Comment by PTYB** [comment]
> > There are logs which show why it ignores items. Also there is no stack size option, there is only a stack value option.
> > EG
> > Ignoring fire rune because 100gp is below stack loot value 1000
> 
> you knew what i meant clearly lol

Just being explicit. I did understood what you mean, didn't want to leave anything up in the air.

**Comment by PTYB** [comment]
Any updates on logs?

**Comment by meatFlaps** [comment]
> Any updates on logs?

I only recently started using the script again, I will let you know

**Comment by meatFlaps** [comment]
> Any updates on logs?

so it will pick up coins, but it will pick up EVERY single coin it sees dropped. even when its under the "stack value" option. 

IE Stack Value is set to 2,000
it picks up a 32 coin drop

I'll remove coins from my ignore list tomorrow and get you logs of it picking up all coins
