### ISSUE TITLE
Add option to choose how we tele to master

### ISSUE THREAD

**Issue by meatFlaps** [PTYB/SlayerIssueTracker#200]
I've brought this up to you a few times now but I realized I didn't make a post on here, or maybe I did and it was closed - please add the option for us to choose how we tele to the master. The script wastes so much time getting to Konar it's crazy, even with house teles in inventory (access to jewelery box in POH) or multiple other teleport options in the bank. The only tele it will use is either minigame tele to Port Sarim or Con Cape tele to Rimmington, boat from Port Sarim to Kourend, and then walk the entire way to Konar

**Comment by SlipperyPickle** [comment]
Another thing to take in account is when it wants to teleport to master with a slayer ring it shouldn't be in combat. In combat it can't select the ring teleport options. Died at Kalphites because of this. If you want I can make a separate bug thread.

**Comment by PTYB** [comment]
Dax should be checking if its in combat

**Comment by PTYB** [comment]
Use the template please

**Comment by meatFlaps** [comment]
> Use the template please

Issue: takes extremely long routes to get to Konar (i'm assuming other masters aswell)
Current behavior: takes extremely long routes to get to Konar (i'm assuming other masters aswell)
Expected behavior: would be nice to add an option into the Slayer settings site where we can choose how to teleport to our respective masters when a task is completed and it requires a new one
Screenshots/Video: N/A
Master: Konar, but would be implemented for all
Task: N/A
Additional information:

**Comment by PTYB** [comment]
I assume this would be POH only?

**Comment by Rallik-Pog** [comment]
Yeah this would be via POH.

**Comment by Rallik-Pog** [comment]
> I've brought this up to you a few times now but I realized I didn't make a post on here, or maybe I did and it was closed - please add the option for us to choose how we tele to the master. The script wastes so much time getting to Konar it's crazy, even with house teles in inventory (access to jewelery box in POH) or multiple other teleport options in the bank. The only tele it will use is either minigame tele to Port Sarim or Con Cape tele to Rimmington, boat from Port Sarim to Kourend, and then walk the entire way to Konar

you need to carry a dramen staff and ardy cloak just in general.

**Comment by meatFlaps** [comment]
> I assume this would be POH only?

POH would be ideal

**Comment by ryant704** [comment]
Issue: Walks to Nieve via any route
Current behavior: Takes any route it can find to nieve
Expected behavior: Check Inventory and and uses teleports (Teleport to house tab, Spirit tree > Gnome stronghold)
Screenshots/Video: N/A
Master: Niever
Task: N/A
Additional information:

**Comment by PTYB** [comment]
Plan to release sometime next week. There will be some criteria though

* Must be at previous task location
* Script toggle on startup to force teleport there.

**Comment by PTYB** [comment]
Now released
