### ISSUE TITLE
Option to attack superiors? 

### ISSUE THREAD

**Issue by Laddad123** [PTYB/SlayerIssueTracker#201]
**Issue:** As of right now, bigger and badder (superiors) are not handled by the script I believe? Or am I wrong? Had a superior spawn after I bought bigger and badder but saw it myself so I atked it in time.
**Expected behavior:** Some option to atk superiors if they spawn? I bring a prayer potion for most mobs for example in case it happens, ofc this could cause a death if you are unlucky, but you can also turn the bigger and bader off for the harder superiors. (most of em are pretty easy but the really high level ones are Idk if this would be too complex to add, but surely would be a nice option to have! :) If it's not too much of a hassle ofc.
**Master:** Every monster that has a superior
**Task:** Ones with superiors

**Comment by PTYB** [comment]
Already raised

https://github.com/PTYB/SlayerIssueTracker/issues/187
