### ISSUE TITLE
Dagannoth at Jormungand's Prison

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#202]
**Issue:** unsupported mob
**Current behavior:** script stops when receives tasks. (possible enhancement to skip unsupported?)
**Expected behavior:** go to rellekka, take the boat from haskell, enter the dungeon and kill mobs
**Screenshots/Video:** 
**Master:** Konar
**Task:** Dagannoth at Jormungand's Prison
**Logs:**
North-East Dagannoth: 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/83980b89-2410-4992-a9c2-5f75f8a57803)
North Dagannoth:
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/5de4a5ba-0872-4697-a657-265cfb2afb6b)
East Dagannoth: 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/4bb60d9c-fbab-4ee8-8424-f50987d60372)

**Additional information:**
Relleka -> Speak with Haskell and take the boat.

Requires completion (or partial?): https://oldschool.runescape.wiki/w/The_Fremennik_Exiles
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/cfc4ee13-a28a-41bb-8bef-30e91def8c11)
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/9a1b3350-bc37-4f5c-a8bf-d72e78e34cad)

**Comment by PTYB** [comment]
Will try adding all these areas this weekend. Will do quest.

**Comment by PTYB** [comment]
Will be added in next release

**Comment by PTYB** [comment]
Added

**Comment by Rallik-Pog** [comment]
I don't see the menu option on the website for Konar

**Comment by PTYB** [comment]
Will be added in next release for konar

**Comment by Rallik-Pog** [comment]
I mispoke, cannon is supported here, but only at the Dagannoth area, not basilisks.

**Comment by PTYB** [comment]
Now released @Rallik-Pog
