### ISSUE TITLE
Basilisks at Jormungand's Prision

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#203]
When getting Basilisks assigned by Konar at Jormungand's Prision, you can kill Basilisk Knights or regular Basilisks

**Issue:** unsupported
**Current behavior:**
**Expected behavior:**
**Screenshots/Video:**
![294578548-9a1b3350-bc37-4f5c-a8bf-d72e78e34cad](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/2d97ac3f-8f90-4619-a7a8-fd5b624f5e3d)

**Master:** Konar
**Task:** Basilisks at Jormungand's Prision
**Logs:** East Basilisks Area
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/7358470d-ffa0-4d71-8283-b00303b1864f)

**Additional information:**
Requires completion (or partial?): https://oldschool.runescape.wiki/w/The_Fremennik_Exiles
V's shield (you should have it unlocked if you are here.) / Mirror Shield

**Comment by PTYB** [comment]
Is the location specifically "Jormungand's Prison" ?

**Comment by Rallik-Pog** [comment]
> Is the location specifically "Jormungand's Prison" ?


"Jormungand's Prison" I believe so yes.
https://oldschool.runescape.wiki/w/Jormungand%27s_Prison

**Comment by PTYB** [comment]
Will be added in next release

**Comment by PTYB** [comment]
Added

**Comment by Rallik-Pog** [comment]
I don't see the menu option on the website for Konar

**Comment by PTYB** [comment]
Woops will be added to konar next release

**Comment by PTYB** [comment]
Now released @Rallik-Pog
