### ISSUE TITLE
Addin Warped Sceptre as a weapon for magic

### ISSUE THREAD

**Issue by Laddad123** [PTYB/SlayerIssueTracker#205]
**Issue:** Not on the config list

**Additional information:** 

Here's a a screenshot, it's 1 handed. 

Warped sceptre

![image](https://github.com/PTYB/SlayerIssueTracker/assets/148270453/62374d67-02e7-4706-9f05-623ef17ad898)

![image](https://github.com/PTYB/SlayerIssueTracker/assets/148270453/f3271892-a35c-4bb4-81d1-51b8bbed5665)

**Comment by Laddad123** [comment]
Reminder ;d

**Comment by PTYB** [comment]
Released

**Comment by Laddad123** [comment]
Hey, you probably missed it.
![image](https://github.com/PTYB/SlayerIssueTracker/assets/148270453/bb0a909b-40af-47ef-9b4a-9feeae9eafac)

It's not there, tried everything i can pretty much and it wont show up
(Yes I know I'm on shield spot on the pic, tried weapon just before and config etc, it's nowhere to be found)
