### ISSUE TITLE
Wrong teleport name Burthorpe (Jewellery Box)

### ISSUE THREAD

**Issue by SlipperyPickle** [PTYB/SlayerIssueTracker#209]
**Issue:** Jewellery box wrong teleport name
**Current behavior:** It tries to teleport to Burthrope
**Expected behavior:** Try to teleport to Burthorpe
**Screenshots/Video:** -
**Master:** -
**Task:** Trolls
**Logs:**
```01-12 19:39:54.025  3760  4348 I com.pty.slayer.logic.inhouse.leafs.TeleportInHouse:  [pool-20-thread-1] 01-12 19:39:54.025  INFO c.p.s.l.i.l.TeleportInHouse - Teleporting with Jewellery Box to Burthrope```
**Additional information:** -

**Comment by PTYB** [comment]
Will be fixed in next release, you might change to change the teleport than change back sorry.

**Comment by SlipperyPickle** [comment]
No worries, ty!
