### ISSUE TITLE
Ankou in catacombs

### ISSUE THREAD

**Issue by kneegr** [PTYB/SlayerIssueTracker#21]
@PTYB 
Issue: when selecting ankou to look at the configuration, or blue dragons, or jellies in the catacombs of kourend section the web page blanks out completely and i have to relog in
Current behavior: when configureing the main things thats fine i have items in every slot, when clicking certain ones like ive mentioned above it just sends a complete white page so far ive only experienced it in catacombs selection ive been going down the list to try and help identify what all ones this happens with 

Expected behavior: the configuration for certain monsters doesnt work on the site 
Screenshots/Video:
default setups:
mele
![image](https://user-images.githubusercontent.com/127032135/223004627-16388169-e77e-46d9-be31-4452c86aeee5.png)

Mele pray
![image](https://user-images.githubusercontent.com/127032135/223004664-012a2458-fd6f-4c3f-ad40-f06d2d09df75.png)

ranged
![image](https://user-images.githubusercontent.com/127032135/223004705-67fe6805-6a95-469d-8b26-7e2ff26e596a.png)

ranged pray
![image](https://user-images.githubusercontent.com/127032135/223004721-3ff996b4-0cd0-4776-85d6-94188f7ad942.png)

this is after i click any of the mentioned configurations 
![image](https://user-images.githubusercontent.com/127032135/223004785-55fe14bb-dddc-4796-a512-eacc4e263a07.png)

this is showing that the setups do work for most configs
![image](https://user-images.githubusercontent.com/127032135/223004881-ab47ec08-0557-4c96-9e70-f13f1960762f.png)

Additional information:
these are the selections that bring me to the white screen 
catacombs

1. ankou
2. blue dragons
3. jellies

stronghold slayer dungeon 

1. aberrant spectres
2. hellhounds

**Comment by PTYB** [comment]
Added a better error screen should display whats wrong.

**Comment by kneegr** [comment]
no error popped up saying what was wrong, but i added a item into the item side casue it was empty and its loading properly now
