### ISSUE TITLE
Barrows equipment not recognized as soon as they degrade, might be expected but is there a way around it?

### ISSUE THREAD

**Issue by Laddad123** [PTYB/SlayerIssueTracker#210]
**Issue:** Barrows gear not recognized as soon as it degrades
**Current behavior:** Will stop when banking, and if I choose a newly repaired pair it'll run/tp straight back as soon as it degrades to 100 and try to find a new repaired pair, instead of using the 100s.
**Expected behavior:** Would be great if barrows gear could somehow be used all the way (full, 100, 75, 50, 25) until it breaks.
**Screenshots/Video:** No video atm but it just stops when at bank cus it cant find the item
**Master:** All
**Task:** All
**Logs:** 
**Additional information:** Pretty much explained most of it I guess but yeah, right now I set it to use 100 gear (need to run and get it down to 100 every time and use the ones I have double pairs of, to make the script be able to run as long as possible when i have barrows gear equipped, mostly just the legs) but if it would be possible to somehow make it recognize it no matter what state it is in, the repairing would be overkill and that we can simply do ourselves but rn it's a littleannoying having to repair it and get it down to 100 every time and then redo the process again as soon as it reaches 75)

**Comment by Laddad123** [comment]
Just noticed there's another thread about this

**Comment by PTYB** [comment]
Not currently sorry, linking to other thread - https://github.com/PTYB/SlayerIssueTracker/issues/173
