### ISSUE TITLE
Add option to fight Hill Giants in catacombs of kourend 

### ISSUE THREAD

**Issue by adjustabundant** [PTYB/SlayerIssueTracker#215]
**Issue:** Vannaka master task Hill Giants task location request
**Current behavior:** Edgeville dungeon
**Expected behavior:** option for kourend catacombs
**Screenshots/Video:**
**Master:** Vannaka 
**Task:** Hill giants
**Logs:**
**Additional information:**

**Comment by PTYB** [comment]
Needs tiles and a good cannon tile(Using location debug in client)

**Comment by adjustabundant** [comment]
Here are the boundaries for the Hill giants area in Catacombs and a snip of the map region, red lines are the coords shown below. Can't use cannons in the catacombs so that part seems not applicable, but let me know if you need any other info

x_min = 1647
x_max = 1659
y_min = 10033
y_max = 10043

![hill_giants_catacombs](https://github.com/PTYB/SlayerIssueTracker/assets/152431223/e9dc9fd2-2c3c-453e-aa7b-f07b2f3cc02e)

**Comment by PTYB** [comment]
Will be added in next release
