### ISSUE TITLE
Spiritual Mages instead of Spiritual Rangers

### ISSUE THREAD

**Issue by meatFlaps** [PTYB/SlayerIssueTracker#218]
**Issue:** Suggesting to killing Spiritual Mages instead of Spiritual Rangers
**Current behavior:** Killing Rangers
**Expected behavior:** Suggesting killing Mages
**Screenshots/Video:** N/A
**Master:** Nieve
**Task:** Spiritual Creatures
**Logs:**
**Additional information:**

Spiritual Mages are WAY better GP/hr than Rangers since they drop tons of Runes aswell as Dragon Boots, there's multiple in the South East corner of the GWD Dungeon. I don't think any legit player would ever choose Rangers over Mages

**Comment by PTYB** [comment]
It has been added
