### ISSUE TITLE
[Enhancement] Spirit Tree Locations

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#229]
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/2bfdfd8a-6882-47a4-ad68-6792e6b39341)

Currently missing the following spirit tree teleports:
East of Poison Waste
Etceteria
Port Sarim
Brimhaven 
Hosidius
Farming Guild

I think for Slayer: Brimhaven would be biggest enhancement.

**Comment by PTYB** [comment]
Added
