### ISSUE TITLE
Adding gear

### ISSUE THREAD

**Issue by getgood2day** [PTYB/SlayerIssueTracker#240]
**Issue: would like to request some gear added**
**Current behavior: gear doesnt show up**
**Expected behavior: Add gear**
**Screenshots/Video:https://i.ibb.co/W5L0XD8/image.png**
**Master: N/A**
**Task: N/A**
**Logs: N/A**
**Additional information:**
**Requesting to be added:**
**Mixed hide boots 29286**
**Mixed hide legs: 29283**
**Mixed hide top: 29280**

**Thank you**

**Comment by PTYB** [comment]
Should be done now
