### ISSUE TITLE
[Enhancement] Change Rune Dragons Prayer Logic To Pray Mage

### ISSUE THREAD

**Issue by iamharmor** [PTYB/SlayerIssueTracker#241]
Suggestion: Change the Protect from Melee in Rune Dragons to Protect from Magic When Prayer is selected in config.

**Additional information: "Rune dragons have accurate and strong attacks, so Bandos, Justiciar, or Barrows equipment is recommended along with Protect from Magic and Piety in tandem to reduce damage taken". I get hit 40's with DFS, bandos, super combat with protect from melee selected, would bandaid trips very nicely.
**Master:** Nieve

**Comment by PTYB** [comment]
Fixed in .76
