### ISSUE TITLE
[Private] Guardian script

### ISSUE THREAD

**Issue by acidic73** [PTYB/SlayerIssueTracker#245]
**Issue:** Does not support Divine runepouch (i)
**Current behavior:** it will bank the runepouch when starting the script
**Expected behavior:** keep the rune pouch to use for npc contact to repair pouches 
**Screenshots/Video:** 
**Master:**
**Task:**
**Logs:**
**Additional information:** exact item name is "Divine rune pouch (I)"

**Comment by PTYB** [comment]
Err this is only for slayer but fixed in .34
