### ISSUE TITLE
Getting stuck in POH trying to get new task.

### ISSUE THREAD

**Issue by nehettinga** [PTYB/SlayerIssueTracker#248]
**Issue:** Teleports to POH after task is completed then errors out and stops script. Been doing this for couple days now. Possibly client error happened around time I updated from R300 to R305. Same issue on beta. My method to slayer master in config is: Spirit tree - gnome stronghold. I have a basic spirit tree in house. When I restart the script outside my POH it dosent even tele to my POH it teles to varrock and runs to spirit tree from there.
**Current behavior:** Error: No task but in house, unsure how to proceed
**Expected behavior:** Use spirit tree to gnome stronghold in POH to get another task from steve
**Screenshots/Video:**
**Master:** Steve
**Task:** None just completed it.
**Logs:**
**Additional information:**

Edit: It seems to not be using my chosen POH methods to get to tasks either, just deciding on its own how it wants to get there. Walker issue?

**Comment by PTYB** [comment]
If you don't specify to go to POH it should never teleport there. Must have misclicked to POH maybe?

**Comment by nehettinga** [comment]
How do I specify it to go to POH, I setup my POH config but say for kraken I tell it to use fairy ring and I have POH teles in my invent it runs to a fairy ring instead of using the POH method setup in my config. Assuming its walker issue because the transport configs seem mostly useless now after update past R300.
