### ISSUE TITLE
Getting stuck on pick up cannon

### ISSUE THREAD

**Issue by getgood2day** [PTYB/SlayerIssueTracker#249]
**Issue: getting stuck on pick up cannon in leaf**
**Current behavior: its getting stuck on pick up cannon in leaf even when I dont have a cannon in my loadout ive tried clearing cache and updating client still doesnt work**
**Expected behavior: finish the task**
**Screenshots/Video:
![image](https://github.com/user-attachments/assets/b13f485d-0aba-4301-9fe0-dbff875e9034)
![image](https://github.com/user-attachments/assets/1dc18932-954d-410f-a0a9-3d5a54b5c0f9)
**
**Master: Konar**
**Task: Jellies**
**Logs:**
**Additional information:**

**Comment by PTYB** [comment]
Should be fixed in latest
