### ISSUE TITLE
Config page doesn't save "Food to heal at bank"

### ISSUE THREAD

**Issue by Zargha1** [PTYB/SlayerIssueTracker#25]
Current behavior: When choosing food from the drop-down menu and clicking the save button, it won't save the configuration
Expected behavior: It saves the configuration
Screenshots/Video: before/after
![image](https://user-images.githubusercontent.com/127086300/223078444-09aac18a-d638-4581-9ee4-c5f29a0117b4.png)
![image](https://user-images.githubusercontent.com/127086300/223078495-718e8a90-f54c-466b-ba4a-71d7754d2100.png)

**Comment by PTYB** [comment]
Still being worked on

**Comment by PTYB** [comment]
Should be fixed in latest version, closing. Re-open if issue persists
