### ISSUE TITLE
Tries to bank while just having arrived when on task

### ISSUE THREAD

**Issue by Zargha1** [PTYB/SlayerIssueTracker#26]
Slayer task: Jelly
Current behavior: After the first time banking when the script is launched, it will grab the specified items from bank (food/alch runes), run to the spot and then immediately try and return to bank.
Expected behavior: After banking it goes back and does task

Inventory it returned with after first time banking:
![image](https://user-images.githubusercontent.com/127086300/223080559-ecd9ce04-2c7c-41b8-a831-1fc2eaf14b4b.png)
[PTYSlayerBanking.txt](https://github.com/PTYB/SlayerIssueTracker/files/10896855/PTYSlayerBanking.txt)

**Comment by PTYB** [comment]
Must have been a smaller area specified in jellies will look into expanding it.

**Comment by PTYB** [comment]
Working on latest as im there. Please let me know if this occurs again
