### ISSUE TITLE
Can we add reg super combat pots to the list of consumables

### ISSUE THREAD

**Issue by kneegr** [PTYB/SlayerIssueTracker#27]
@PTYB  idk if there is a list of what pots to use, but when i bring super combat pots it doesnt use them, it was using super attack and super str im pretty sure, just wanted to save some kind of inv space.

**Comment by PTYB** [comment]
Will add them later today.

Can you please write the exact name

**Comment by kneegr** [comment]
sorry it took so long 
![image](https://user-images.githubusercontent.com/127032135/225374228-376cc8d7-a341-465f-82d2-d28e3301a68c.png)

**Comment by PTYB** [comment]
Will have to wait till Sunday sorry, out until then

**Comment by PTYB** [comment]
Marking as resolved, reopen if issue
