### ISSUE TITLE
brimhaven tasks

### ISSUE THREAD

**Issue by kneegr** [PTYB/SlayerIssueTracker#28]
when doing brimhaven tasks, it gets everything, runs to brimhaven, goes to the cave, but when it pays the guy to get it, it pays, then keeps trying to repay and doesnt just walk into the dungeon, ill have to try to pull logs for this i dont have any currently i happened to look over on a brimhaven task and it was just standing trying to pay over and over again 
@PTYB

**Comment by kneegr** [comment]
isnt just one specific brimhaven task it happened on fire giants and on greater demons

**Comment by PTYB** [comment]
Please use template and supply logs.

**Comment by PTYB** [comment]
I believe this is a web walker issue.

**Comment by PTYB** [comment]
Issue has been raised with Elias

**Comment by kneegr** [comment]
have a new task and the same thing keeps happening, it just runs up to the guy and keeps trying to pay, i even payed the 1m for perm access since i seem to get this place alot on this acc, and it still just asks to pay, doesnt seem to check if its paid it just seems to spam try to pay and after successfull payments keeps trying to pay

**Comment by PTYB** [comment]
Best ask elias to fix this. If you can get me the varpbit I can add logic for this

**Comment by PTYB** [comment]
Elias has fixed this by just using pay on the door

**Comment by Rallik-Pog** [comment]
Related bug: Default coins brings enough for the dungeon only, but you cant get in if you fairy ring to use a boat.
Solution bring add 30 coins to pay for ardounge boat fare. Or change it yourself for setups like I did.
