### ISSUE TITLE
bronze drag in brimhaven dung

### ISSUE THREAD

**Issue by kneegr** [PTYB/SlayerIssueTracker#30]
@PTYB 
Issue: not attacking dragons
Current behavior: runs to drags n teles to bank before doing anything
Expected behavior: to do the task and bank when inv full 
Screenshots/Video: Issue:

Additional information:

https://user-images.githubusercontent.com/127032135/226208689-5ea61394-efd9-410e-926d-1574c8015c07.mp4
[dump.txt](https://github.com/PTYB/SlayerIssueTracker/files/11012279/dump.txt)

just seems to run there then tele to bank and run back and repeat, ive changed from extended superantifire to just regular super antifire and itll use them but it runs back to thebank before even attacking

**Comment by PTYB** [comment]
Video is not playing for me.

Seems to say 
Needs to bank?[S]

**Comment by kneegr** [comment]
inv is empty, where should i upload videos to link them any reccommendations?

**Comment by kneegr** [comment]
looking on the slayer config page, there are two bronze dragons for brimhaven

**Comment by PTYB** [comment]
That might be the issue, I probably have to remove a bad one

**Comment by kneegr** [comment]
[dump.txt](https://github.com/PTYB/SlayerIssueTracker/files/11012430/dump.txt)
just incase here is a fresh logs of it happening, i reinstalled pow, did dev version, and started the script n stopped it after it ran to the dragons then banked

**Comment by PTYB** [comment]
I deleted the extra bronze dragon, can you send me the name of super anti fires and I will add them to the consumable list for them.

**Comment by PTYB** [comment]
Various antifires have been added.
