### ISSUE TITLE
Hellhounds Taverley Dungeon

### ISSUE THREAD

**Issue by coolmax750** [PTYB/SlayerIssueTracker#32]
Task name: Hellhounds in Taverly Dungeon
Npc Name:Hellhound
Npc Location(Tile) (X=2867, Y=9840) (LocalX=51, LocalY=48) this is confusing to me i put the spawn for the one that can be safe spotted behind a rock but if i were to want to kill them efficiently with a cannon i would go down the cliff im just not sure how to put the tile locations if its better to show photos or coordinates 
Safespot?: (X=2870, Y=9844) (LocalX=54, LocalY=52)
Prayer recommended: depends on combat level higher combat could do this task with food most people would cannon with protect from meele 
Antipoison/Antifire: blue dragons might hit you once after going through the tunnel but if food brought then can heal
Slayer Gear/Additional requirements:
Closest bank: falador west bank

**Comment by PTYB** [comment]
Has been added awhile ago
