### ISSUE TITLE
Custmize looting ( not a bug but idea)

### ISSUE THREAD

**Issue by Litag10** [PTYB/SlayerIssueTracker#33]
I might not be the best at explaining, but I'll try :D

My idea is that where you select gear for task, u can select what you want to loot too. 

option 1 Can set a price Example: Loot everything over 1k

option 2

get up everything that monster drop, and you choose by clicking on the different ones.

Example: hill giants  looting table: i select death runes, blood runes, law runes, big bones, but not body talisman although it is worth more than much else I choose.

**Comment by PTYB** [comment]
Already ticket for this - https://github.com/PTYB/SlayerIssueTracker/issues/5 (Option 2)

**Comment by PTYB** [comment]
Added global configuration in configuration page.

Will tidy up the items this weekend sometime(To have unfiltered list)

**Comment by PTYB** [comment]
Items tidied up

**Comment by PTYB** [comment]
Released so closing
