### ISSUE TITLE
Loadout Editing Behaviour issue

### ISSUE THREAD

**Issue by Zargha1** [PTYB/SlayerIssueTracker#34]
Issue: Loadout Editing Behaviour issue
Current behavior: While editing loadout, sometimes the existing off-hand doesn't disappear when changing it.
Expected behavior: Doesn't have to re-open page to change off-hand
Screenshots/Video:
![image](https://user-images.githubusercontent.com/127086300/229618955-0d3e6348-bcc9-4333-a90d-c0f1fad9ba91.png)

**Comment by PTYB** [comment]
Fixed in latest build
