### ISSUE TITLE
Config removes all items when "x" is pressed

### ISSUE THREAD

**Issue by Zargha1** [PTYB/SlayerIssueTracker#35]
Issue: Config removes all items when "x" is pressed
Current behavior: When clicking the "x" to remove a specific item from a config, it'll remove all (base?) items except for food
Expected behavior: When clicking the "x", remove only the item I pressed x for 
Screenshots/Video: 
![image](https://user-images.githubusercontent.com/127086300/229709767-0f9fe0d5-e228-472b-976c-3575148f4979.png)
![image](https://user-images.githubusercontent.com/127086300/229710037-e0038a19-54ec-492d-8994-7e5ab74659c6.png)

**Comment by PTYB** [comment]
Please test in latest version

**Comment by Zargha1** [comment]
Doesn't appear fixed

**Comment by PTYB** [comment]
I just tested it again and it was fine(In live), maybe your browser was cached?

**Comment by Zargha1** [comment]
Yes it's been fixed!! Thank you!
