### ISSUE TITLE
When taking too much damage it will teleport

### ISSUE THREAD

**Issue by Zargha1** [PTYB/SlayerIssueTracker#36]
Task: Iron dragon - Isle of Soul
Current behavior: When taking a hit from Iron Dragons on it will teleport away (usually under 50% hp) while inventory has plenty of food
Expected behavior: Heal the damage taken by using the food in inventory
Screenshots/Video: Screenshot of inventory when it happened
![image](https://user-images.githubusercontent.com/127086300/229802458-5bf43cfb-6584-44b6-9ad6-594a92468a6b.png)

Additional info: Can't check if this is task specific. Could it be that because there is now an extended antifire potion(3) in inventory, instead of extended antifire potion(4) es specified in the config, that it tries to bank?

**Comment by PTYB** [comment]
Had missing food for manta ray.

Added alot more food and super/etended antifire

**Comment by Zargha1** [comment]
Now it just runs back to bank once arriving at destination area

![image](https://user-images.githubusercontent.com/127086300/229924082-c57495d8-4aed-4885-8a21-8ac44edf57f8.png)

**Comment by PTYB** [comment]
Can you grab logs please
