### ISSUE TITLE
Vannaka - Blue Dragons -> Walks to Kourend Dungeon for brutal dragons then tries to bank (loops)

### ISSUE THREAD

**Issue by Zargha1** [PTYB/SlayerIssueTracker#38]
Slayer task: Blue Dragons
Slayer master: Vannaka
Current behavior: It grabs the right gear from the bank, then walks to the area. Note that in the config it says "Taverly Dungeon" for blue dragons, but it walks to brutal blue dragons in Kourend Dungeon. 
Expected behavior: Walk to either of the dragons and starts killing them

[PTY Slayer - Vannaka - Blue Dragons - Banking issue.txt](https://github.com/PTYB/SlayerIssueTracker/files/11173410/PTY.Slayer.-.Vannaka.-.Blue.Dragons.-.Banking.issue.txt)

**Comment by PTYB** [comment]
Please try on latest
