### ISSUE TITLE
Bronze Dragons - Vannaka

### ISSUE THREAD

**Issue by Zargha1** [PTYB/SlayerIssueTracker#40]
Issue: Bronze dragon task from Vannaka preps for brimhaven bronze dragons (?) also doesn't copy proper config
Current behavior: Withdraws default ranged config + brimhaven entry stuff, then goes to brimhaven.
Expected behavior: Withdraws specific config for Bronze Dragons and goes to Catacombs of Kourend as shown in the config destination 
Screenshots/Video:
Additional information:

**Comment by PTYB** [comment]
This resolved now?

**Comment by Zargha1** [comment]
Yes!

**Comment by PTYB** [comment]
Just tested and it went to brimhaven for me? Can you try updating your config and saving and see if it happens
