### ISSUE TITLE
[Bug] Dagganoth wrong pathing

### ISSUE THREAD

**Issue by Zargha1** [PTYB/SlayerIssueTracker#41]
Issue: Both the Killerwatt task from Vannaka and the Dagganoth task under the lighthouse from Konar path wrongly, making them loop in circles forever.
Current behavior: Killerwatt: Does go up the staircase but doesn't enter the killerwatt portal in Draynor manor. If you put it in the room with the portal it will click the portal, but it doesn't go there itself. Once you do that manually OR click the portal it runs as expected.

Dagganoth: It will also go up to the lighthouse stairs, rather than take the ladder downwards to the dagganoth, where it's supposed to be. If you click the ladder down it will the n resume task no problem.
Expected behavior: Pathing properly to both mobs.

I forgot to get logs, I can get them if necessary

**Comment by PTYB** [comment]
Will have to raise with Elias

**Comment by PTYB** [comment]
Killerwats should be fixed in latest version

**Comment by PTYB** [comment]
Travels to task fine now.
