### ISSUE TITLE
Hellhounds Karuulm Slayer Dungeon

### ISSUE THREAD

**Issue by Zargha1** [PTYB/SlayerIssueTracker#42]
Task name: hellhounds in the Karuulm Slayer Dungeon
Npc Name: Hellhound
Npc Location(Tile): 1336, 10205, 2
Safespot?: No
Prayer recommended: No
Antipoison/Antifire: No
Slayer Gear/Additional requirements: Boots of stone
Closest bank: Karuulm bank

**Comment by PTYB** [comment]
Will be in next release

**Comment by PTYB** [comment]
Released

**Comment by Zargha1** [comment]
I'm guessing it doesn't have the right area code, given that it will stay on "walk to area" even if already in the area and attacking hellhounds

**Comment by PTYB** [comment]
Tested working yesterday reopen if issues
