### ISSUE TITLE
Vannaka Task - Infernal mages

### ISSUE THREAD

**Issue by Zargha1** [PTYB/SlayerIssueTracker#43]
Task name: infernal mages
Npc Name: Infernal mage
Npc Location(Tile): 3437, 3571, 1
Safespot?: No
Prayer recommended: Magic
Antipoison/Antifire: No
Slayer Gear/Additional requirements:
Closest bank: Canifis

**Comment by PTYB** [comment]
Should be added and release now. Comment when you can verify its working fine

**Comment by Zargha1** [comment]
Doesn't work unfortunately

**Comment by Zargha1** [comment]
Works now btw!
