### ISSUE TITLE
QOL rings and amulets

### ISSUE THREAD

**Issue by swordux15** [PTYB/SlayerIssueTracker#44]
I've noticed that when you have a glory or a ring of wealth equipped with a specific enchantment lets say (6) as soon as it uses it, it becomes confused and wants to bank to get rid of the (5) and go to (6) again.

solution : don't know how possible this is , but you could make it so that the item with any amount of charges is treated the same AKA: glory (1) (2) .... (6) would be treated as a charged amulet and it would only swap when charges reach 0

**Comment by PTYB** [comment]
Merging with https://github.com/PTYB/SlayerIssueTracker/issues/29
