### ISSUE TITLE
Combat suggestion

### ISSUE THREAD

**Issue by swordux15** [PTYB/SlayerIssueTracker#45]
Would be nice (especially for lower level accounts) to add the ability to switch between styles.

Example: you set every (x) level that you swap styles from attack training to defence to strength (same thing can apply later to range and mage if defence levels would be needed).

also would be nice if you could select witch stats to rotate trough for example you could exclude defence and only rotate between strength and attack

I understand that this is a niche thing but would be nice to see :)

**Comment by PTYB** [comment]
No plans to implement, this can request in the future and we may revisit.
