### ISSUE TITLE
Witchaven dungeon hellhounds

### ISSUE THREAD

**Issue by Enskauning** [PTYB/SlayerIssueTracker#47]
Task name: Hellhounds 
    Npc Name: Hellhounds
    Npc Location(Tile)
    Safespot?: yes https://gyazo.com/48659a5aa7f6f3d641d6acd7f0110120
    Prayer recommended: no
    Antipoison/Antifire: no
    Slayer Gear/Additional requirements: no
    Closest bank: ardougne
Konar
Need to complete a small puzzel 1 time by pulling levers.  https://oldschool.runescape.wiki/w/Witchaven_Dungeon#The_Puzzle

**Comment by PTYB** [comment]
Need the exact text for witchhaven

**Comment by PTYB** [comment]
Added latest version(Got task)
