### ISSUE TITLE
Konar missing areas

### ISSUE THREAD

**Issue by Enskauning** [PTYB/SlayerIssueTracker#48]
Task name: Death plateu Trolls
    Npc Name: Troll
    Npc Location(Tile) death plateu
    Safespot?: no
    Prayer recommended: yes/no
    Antipoison/Antifire: no
    Slayer Gear/Additional requirements: no
    Closest bank: Burthorpe

    Task name: Fire giants Waterfall dungeon
    Npc Name: Fire giant
    Npc Location(Tile) Inside waterfall dungeon
    Safespot?: No
    Prayer recommended: Yes/no
    Antipoison/Antifire: no
    Slayer Gear/Additional requirements: no
    Closest bank: Barbarian assault

Srry dont know how to get tile. 

Need rope for waterfall dungeon.
Need to pray for range while running up to death plateu.

**Comment by PTYB** [comment]
Please use exact text for task area or it will not work.

**Comment by Enskauning** [comment]
> Please use exact text for task area or it will not work.

Okay will do!

**Comment by PTYB** [comment]
Fire giants should be fixed in latest

**Comment by Rallik-Pog** [comment]
It asks for Glarials amulet, though it's not needed after the quest has been completed.

09-18 09:50:54.884  6144  6541 I COn     : Missing Glarial's amulet 1 | 0 found
