### ISSUE TITLE
will not attack Earth warrior or Ice warrior ( using lates beta updated today)

### ISSUE THREAD

**Issue by Litag10** [PTYB/SlayerIssueTracker#50]
it never attack them, in the beginning it gets attacked by them, but when aggro is over it just stay there

and it will not loot anything but that can be a user issues? :P 
![346132454_2208144016042888_1785785037434716826_n](https://github.com/PTYB/SlayerIssueTracker/assets/128861755/8b2a4945-4506-4475-ad39-4f8e2cf97336)
[logslay.txt](https://github.com/PTYB/SlayerIssueTracker/files/11519010/logslay.txt)

**Comment by PTYB** [comment]
Closing as it was client bug
