### ISSUE TITLE
Karuulm Slayer Dungeon

### ISSUE THREAD

**Issue by swordux15** [PTYB/SlayerIssueTracker#52]
The bot consistently crashes when entering  Karuulm Slayer Dungeon and walking past the TzHaar looking dudes, if i manually place it on another floor you can avoid it, so far this has only happened on the greater demon task, but I havent goten any others in the Karuulm Slayer Dungeon.

![image_2023-05-20_000337103](https://github.com/PTYB/SlayerIssueTracker/assets/132946335/004184d0-b551-4c61-abf2-73b1e34d8b53) 
sc of where it crashes, don't have any way of recording atm.

**Comment by PTYB** [comment]
Web walking issue, might have to add my own walking logic

**Comment by PTYB** [comment]
Can you test in latest version, released some updates

**Comment by PTYB** [comment]
Closing, reopen if issues
