### ISSUE TITLE
Bot does not attack after agro timer 

### ISSUE THREAD

**Issue by swordux15** [PTYB/SlayerIssueTracker#53]
Dont know if this is related to the my previous post (probably not) but when I walk to the Karuulm Slayer Dungeon Greater demon manually (I let it do the walking from 2nd floor onwards) the bot gets stuck on last leaf: wait and does not attack the demons.

Edit: changed the title because I noticed it  with more than one task now, where it is just stuck waiting after the agro timer ends, dont know if its something on my end but it was working fine a day ago and i haven't changed anything.... 

Edit 2: noticed that it does not loot anything as well... seems like the whole combat/looting portion is broken, still eats and sips potions tho.

Edit 3: saw some post about it going on with other scripts guess its a client problem.

**Comment by PTYB** [comment]
Assume its fixed after client fixes?
