### ISSUE TITLE
Vannaka Hellhounds stops script

### ISSUE THREAD

**Issue by Zargha1** [PTYB/SlayerIssueTracker#54]
Issue:  As title
Current behavior: It will stop the script, as if it can't perform the task
Expected behavior: Gets me smouldering stone
Logs: 
[PTY Slayer Hellhounds Vanaka.txt](https://github.com/PTYB/SlayerIssueTracker/files/11618772/PTY.Slayer.Hellhounds.Vanaka.txt)

**Comment by PTYB** [comment]
Fixed, was recent obsfucation issues
