### ISSUE TITLE
Hellhounds Taverley Dungeon

### ISSUE THREAD

**Issue by Klazha** [PTYB/SlayerIssueTracker#55]
Issue: Script stopping on "Hellhounds" - "Taverley Dungeon" task.
Current behavior: Stops script immediately.
Expected behavior: Continue running to Taverley Dungeon for task, as well as possibly using agility shortcuts.
Screenshots/Video: N/A - Script just stops after getting assignment.
Additional information: If any additional information is needed, I can update post with logs or whatever is needed. (Using Konar as master)

**Comment by PTYB** [comment]
is "Taverly dungeon" the exact name including caps etc

**Comment by Klazha** [comment]
Corrected now, Taverley dungeon -> Taverley Dungeon

Updated Post: Corrected name using correct capitalization for "Taverley Dungeon".

**Comment by PTYB** [comment]
Should be fixed as I have run this task
