### ISSUE TITLE
Dagannoth: In the Lighthouse

### ISSUE THREAD

**Issue by Klazha** [PTYB/SlayerIssueTracker#56]
Issue: Seems to be having issues in front of the "strange wall", returning to bank.
Current behavior: Attempts to click the inside "Iron Ladder" towards the Dagannoth.
Expected behavior: Click the "Iron Ladder" just south of the "strange wall" to return to bank.
Screenshots/Video: Can send screenshots/video via Discord if it is needed.
Additional information: It seems that it got stuck after filling the inventory to return to bank to deposit the items it collected that run. Last leaf is stating: "Go to bank".

Edit: Grammar corrections.

**Comment by PTYB** [comment]
More recent ticket has more info
