### ISSUE TITLE
Ankou Stronghold Slayer Cave - Konar Task

### ISSUE THREAD

**Issue by iamharmor** [PTYB/SlayerIssueTracker#57]
Script seems to get confused and tell itself to go to bank constantly, did it multiple times but I decided to record it doing it.

Script seems to struggle to detect cannon is inactive, looks like it just has an initial process to set it up but with errors and it returning it might not interact sometimes with it at all. 

When I first ran it and it ran back to the bank and returned it didn't eat at all and I watched it to see if it might figure it out and it just died. 
https://gyazo.com/4a15740df9e45ce78737217bc1c39522

Heres a screenshot of before recording when it ran to bank and withdrew nothing and decided to go back. https://gyazo.com/68d867738d6c4b6bbb6ad69147bbebb9

When grabbing a task, it would be cool if it could restore prayer back up to full, you'll finish a task and itll rebank and not restore prayer from where it was at while at bank, just a request.

https://www.youtube.com/watch?v=tOKEbQL8VnY <--------Video of task 4:57 is when it messes up

I got a retask of Mountain trolls and it did the same thing and told itself to immediately rebank, is it possibly due to it forcing itself to have a certain amount of food?
[gagek.txt](https://github.com/PTYB/SlayerIssueTracker/files/11713562/gagek.txt)

**Comment by iamharmor** [comment]
Ankou setup: https://gyazo.com/21e4ef25a500329a9ad50267e6ef1f83
Mountain Troll setup: https://gyazo.com/e093740fa3b9265202573da505f4d8f9
any tips how u personally set yours up not sure why it cant prioritize the fact that I have prayer on and 8 super restores and it can sit there and last for a long time

**Comment by PTYB** [comment]
I haven't setup super restores for prayer restore, I will add them to the list. Seems a bit expensive when you can just use prayer potions.

**Comment by iamharmor** [comment]
We eat well out here, thanks again.
