### ISSUE TITLE
Died at Greater Nechs in Kourend

### ISSUE THREAD

**Issue by Dyland0r** [PTYB/SlayerIssueTracker#58]
Started script, ran perfect, set everything up as he should have, walked to Greater Nechryael, killed 10+ fine.

Issue:
For some reason after the death of a Greater Nechryael he was just standing there instead of attacking the next one, so I quickly plugged my phone in and opened up the logs and let it just run its course until he eventually ran out of prayer and then died.

Current Behaviour: 
Set it back up and it's running smooth again, not sure if it has something to do with killing the spawns they summon.

Expected behavior:
To continue fighting and drinking potions.

Additional information:
Not fussed about the death or anything just wanted to post the logs and hopefully help with something.
[Death At Nechs.txt](https://github.com/PTYB/SlayerIssueTracker/files/11713605/Death.At.Nechs.txt)

**Comment by PTYB** [comment]
Sounds like the script for some reason stalled, my guess it would be something to do with the loot tracking mechanic. Will take a look into it cheers.

**Comment by Dyland0r** [comment]
It's running on a phone - Motorolla G32 (seems like a pretty sturdy phone compared to how my computer handled Bluestacks I'd say it's equivlent to the 4 core/ram not 100% sure though)
