### ISSUE TITLE
Script Request - Checking of Slayer Task

### ISSUE THREAD

**Issue by iamharmor** [PTYB/SlayerIssueTracker#59]
Very minor, if when you start the script it would walk to a bank to withdraw an enchanted gem to check task would be appreciated, appears you have to have an enchanted gem in your inventory when you start the script for it to recognize to check it, i assume it was prioritized around people wearing slayer helms and it checking that.
I have to withdraw the gem in my bank for it to start the process of checking and then it wont rebank it either itll just go on with the task, but as soon as its checked initially you have visuals of how far along you are in the task.

https://gyazo.com/e4bafad31dd7afba38f413136580b1cb <---- Gif

**Comment by iamharmor** [comment]
definitely would be super nice, got the slayer helm, but its the same thing you have to start the script with either a slayer helmet equipped or in inventory and it does the gearing after this precheck, great QOL addition.

**Comment by PTYB** [comment]
Will be added next release

**Comment by PTYB** [comment]
Released in .30

**Comment by Rallik-Pog** [comment]
Does not withdraw Slayer Helmet (i) from bank to check task, but will check it if it's equipped.
