### ISSUE TITLE
[Bug] Disable prayer when running to master

### ISSUE THREAD

**Issue by iamharmor** [PTYB/SlayerIssueTracker#60]
Would it be possible for a priority system to be added when prayer is enabled for a task and it sees it has super restores and stays, it will proceed to rebank when it runs out of food, im running lots of range pots, cannons, teleports, pray pots, so i only bring 5 food and it lasted 4 min until it told itself to rebank.

Video : https://youtu.be/-CTQbH2sMYc
logs aswell ofc.
[FOODPLS.txt](https://github.com/PTYB/SlayerIssueTracker/files/11715269/FOODPLS.txt)

**Comment by iamharmor** [comment]
brownie points, middle of video you see a player raging over me crashing them with my cannon luuuul was pretty funny

**Comment by iamharmor** [comment]
I spotted a major issue for me, it eats my food to prioritize picking up big bones, might just have to map out every single item for it to ignore to figure out a steady balance of that, but i guess a better request would be for it to not eat the food to pick up 100gp bones or 200 earth runes or 1 strawberry seed, maybe prioritize not eating if value isnt greater than 5000gp idk

**Comment by iamharmor** [comment]
If I can add on this request, have the script turn off prayer as it finishes a task, currently it will just sit on the protection its on and proceed to run to slayer master(konar), is this a webwalker thing?

**Comment by PTYB** [comment]
You can just add the bones to the ignore list

**Comment by iamharmor** [comment]
yea i did, but heres an example it was teleing to master and my prayer was draining down as far as the other thing
https://gyazo.com/eb46b671cf957433a0d10ef0908bafe6

**Comment by Rallik-Pog** [comment]
Leaving prayer on is still buggy for some tasks--- Sometimes it shuts it off. 
Seems to leave it on after using ardy cloak teleport.

**Comment by Rallik-Pog** [comment]
confirming-- it always leaves prayer on when teleporting out with Ardounge Cloak
