### ISSUE TITLE
Script does not loot brimstone keys assigned from Konar Tasks

### ISSUE THREAD

**Issue by iamharmor** [PTYB/SlayerIssueTracker#61]
Was doing trolls - South of mount, assigned by konar, did not pick up the brimstone keys dropped.
https://gyazo.com/93d79f115119a55c69639e81422ad334

**Comment by iamharmor** [comment]
I looted the key manually and pressed resume and it proceeded to afk on last leaf: killing npc curent task: mountain troll and just died :(

**Comment by PTYB** [comment]
Discussed this in discord. Not related to brimstones but another issue.
