### ISSUE TITLE
Wrong Item ID for item to ignore - Raw Mackeral

### ISSUE THREAD

**Issue by iamharmor** [PTYB/SlayerIssueTracker#62]
Added Raw Mackeral(353) to items to ignore and it proceeded to pick it up in a task with a fresh restart, maybe its a different item ID.

https://gyazo.com/140cf59a61ce0fafb4841bbde7afeb87
https://gyazo.com/0e8e52c8465ba3a1096bb4a56bfd0eca
https://gyazo.com/b5312c8549f944d214aa6dc54ab3e3e2

**Comment by iamharmor** [comment]
Can't find Steel axe to add items to ignore. I see other axes but that one. https://gyazo.com/246c5bf42710b1d34afede2e446dd408

**Comment by PTYB** [comment]
Noted is 354
