### ISSUE TITLE
Script does not recognize cannon usage in Isle of Souls

### ISSUE THREAD

**Issue by iamharmor** [PTYB/SlayerIssueTracker#63]
Had a cannon in my inventory through my setup and the script would not place it down, you can use a cannon in Isle of Souls.
Setup: https://gyazo.com/68761e9290f1b44ea7540efcdc2686fc
Video: https://youtu.be/FD5LWWgXB5Q

**Comment by PTYB** [comment]
It has been added, might need to re-release the backend.
