### ISSUE TITLE
Script Request - Item ID's to add megalist

### ISSUE THREAD

**Issue by iamharmor** [PTYB/SlayerIssueTracker#65]
Requests to add item id's to system so we can ignore them.
feel free to paste any not currently available.
For now
~~- Javelins (iron,steel,etc.)~~
~~- Ensouled heads~~
-   Ensouled Hellhound Head
- Scaly Blue Dragonhide
- Noted Raw Mackeral(354) can only find the unnoted(353) in the list, can you confirm if im tripping or what

Leaving open for a week until i scratch every item surface.

**Comment by iamharmor** [comment]
- Noted Pure Essence(currently only unnoted is available, tasks drop noted)

Pure essence | 7937 | noted

**Comment by PTYB** [comment]
Closing as over 1 week has occured. Should be resolved when I add gp price checking for items
