### ISSUE TITLE
Light sources in Lumbridge Swamp Caves

### ISSUE THREAD

**Issue by Litag10** [PTYB/SlayerIssueTracker#69]
can there be added more option for Light source?

will be usefull for ironman, almost all ironman have Firemaking cape and Bruma torch from wintertodt, and maybe firemaking cape as best cape too. 

https://oldschool.runescape.wiki/w/Light_sources

**Comment by PTYB** [comment]
Which one do you think it should default to?

**Comment by Litag10** [comment]
Looks like it can use FM cape? First time it didn't go there, but after i posted, it will....

**Comment by PTYB** [comment]
It can't default to FM cape since not everyone will have it.

**Comment by Litag10** [comment]
Check equipted  if FM cape is  then u have light source. Maybe that already works. Not used the script for a while
