### ISSUE TITLE
[Enhancement/Script Request] - Last task toggle

### ISSUE THREAD

**Issue by Klazha** [PTYB/SlayerIssueTracker#70]
Very minor possible enhancement/script request, to set a checkbox on the paint for a 'Last task' toggle/method.

Toggle checkbox>Finish task>Grab new task>Stop script

Would be highly appreciated, but is an extremely minor request. <3

**Comment by PTYB** [comment]
Where would it stop? After finishing the task(Would be possible to die in aggro areas)? At the slayer masteR?

**Comment by Klazha** [comment]
Slayer master, please and thank you! Makes it a bit easier for end of night runs in my case.

**Comment by PTYB** [comment]
Implemented now, closing
