### ISSUE TITLE
Konar (Fire Giants Karuulm Slayer Dungeon) Game Crash bug.

### ISSUE THREAD

**Issue by Dyland0r** [PTYB/SlayerIssueTracker#71]
Issue: Game crashes while trying to get to Fire Giants in the Karuulm Slayer Dungeon.
Current behavior: Gears up fine, walks to the dungeon fine, stops near the staircase and the game crashes.
Expected behavior: To continue to Fire Giants and pillage them for their loot and experience.
Screenshots/Video: Do not have sorry.
Additional information: This also happened to me on a task in the same dungeon the other week(don't think it was Fire Giants though), but when I ran the script again he got to the task and completed it.
But with this task it crashes every time, I thought it might of been the memory leak last time but now I am thinking maybe something to do with this area, no real idea though so here are the logs :>
[SlayerCrash.txt](https://github.com/PTYB/SlayerIssueTracker/files/11769363/SlayerCrash.txt)
[SlayerCrash2.txt](https://github.com/PTYB/SlayerIssueTracker/files/11769367/SlayerCrash2.txt)

EDIT:
If it is any useful bit of information, just before it crashes the paint comes up saying
Last leaf: Wyrms
Task: Fire Giants

**Comment by PTYB** [comment]
Issue with web walking, I think I pushed something yesterday to help with this

**Comment by Dyland0r** [comment]
Could not get this to replicate in Karamja again, ran your script and he completed and done the task fine, I think this issue is solved!
