### ISSUE TITLE
lizard task, walking to lizard and bank

### ISSUE THREAD

**Issue by Litag10** [PTYB/SlayerIssueTracker#72]
[Nytt tekstdokument (3).txt](https://github.com/PTYB/SlayerIssueTracker/files/11772387/Nytt.tekstdokument.3.txt)

log is from updated beta, video is not from latest beta, but same thing.
https://www.youtube.com/watch?v=I30_aEGCWnE

**Comment by PTYB** [comment]
I think I will have to do some custom logic for handling waterskins

**Comment by PTYB** [comment]
This should have been resolved
