### ISSUE TITLE
Script Does Not Turn Off Prayer After Task Completion

### ISSUE THREAD

**Issue by iamharmor** [PTYB/SlayerIssueTracker#73]
https://gyazo.com/82db687c9fef7cc3eff951d259240e48

brownie points if the script replenishes prayer back up to full while banking.
[pray.txt](https://github.com/PTYB/SlayerIssueTracker/files/11779695/pray.txt)

**Comment by PTYB** [comment]
This is fixed, although master has yet to be done.
