### ISSUE TITLE
Bank issues

### ISSUE THREAD

**Issue by Litag10** [PTYB/SlayerIssueTracker#74]
script do redy armor ect but not inventory, just standing there

user issues? or script/client?
![image](https://github.com/PTYB/SlayerIssueTracker/assets/128861755/2d89e11e-7193-44d4-a059-b4acb5e40841)

[bank.txt](https://github.com/PTYB/SlayerIssueTracker/files/11781837/bank.txt)

https://youtu.be/AImYLG5GFtQ

**Comment by Litag10** [comment]
Only happend at harpie bug tasks

**Comment by Patyfatycake** [comment]
There is 0 powbot logs in that. Did it have enough food? What amulet was it supposed to wear

**Comment by Litag10** [comment]
Yea, alot of food, was Diamond necklace. (did never get it from bank so I tryed without too) only havong this issue with harpie bugs.

**Comment by PTYB** [comment]
I thought I had a failsafe but I will have to add another to stop if it missing an item
