### ISSUE TITLE
Just an Idea, Housing Transportation

### ISSUE THREAD

**Issue by RiskyReward** [PTYB/SlayerIssueTracker#76]
Create an option to teleport using POH. Cuts down significant walk time. If you need a house to reference, I have a character I can lend out whenever you get the time to do it.

**Comment by Rallik-Pog** [comment]
To add to this; rejuvenation pool support. Mounted Xerics, Digsite pendant, box, nexus etc.

**Comment by PTYB** [comment]
Currently in progress.

**Comment by PTYB** [comment]
Implemented/in progress still, closing.
