### ISSUE TITLE
[Bug] Does not stop with missing equipment

### ISSUE THREAD

**Issue by winslowcode** [PTYB/SlayerIssueTracker#77]
Issue: Stuck on bank with task of "setup equipment"
Current behavior: Bot stuck on banking logic trying to find item(boots of stone) that is not present in bank or player
Expected behavior: Stop script with error message prompting player to obtain boots of stone or variant
Screenshots/Video:
Additional information: Hell hound task for the Karuulm Slayer Dungeon

**Comment by PTYB** [comment]
Should be resolved now, sorry for the long wait.

**Comment by PTYB** [comment]
Closing since 3 weeks. Feel free to comment if issues @winslowcode
