### ISSUE TITLE
Bronze Dragons at Brimhaven Dungeon Bank Spam 

### ISSUE THREAD

**Issue by RiskyReward** [PTYB/SlayerIssueTracker#79]
As soon as the bot reaches the bronze dragons, it just teleports to bank for some reason.
[bronze dragon bank spam log.txt](https://github.com/PTYB/SlayerIssueTracker/files/11901984/bronze.dragon.bank.spam.log.txt)

**Comment by PTYB** [comment]
Metal dragons need antifire, otherwise there is no good way to kill them. Also use the template next time.

**Comment by RiskyReward** [comment]
I have a dragonfire shield, so youre saying I need to take the anti-fire potion as well?

**Comment by PTYB** [comment]
Yes, you might be able to turn off the antifire required configuration in GUI(Never tested)

**Comment by RiskyReward** [comment]
Ah gotcha and apologies for not using the template

**Comment by PTYB** [comment]
The main reason I have never tested because catacomb metal dragons without antifire would be hell.

**Comment by RiskyReward** [comment]
I get hit for 2's with just the dragonfire shield, I usually just take 10 sharks and clear the task just fine. but everyone's circumstances are different so I wont be ignorant

**Comment by RiskyReward** [comment]
Ill take a potion np
