### ISSUE TITLE
Blue Dragon Task, Bank Loop

### ISSUE THREAD

**Issue by winslowcode** [PTYB/SlayerIssueTracker#81]
Issue: On full inventory bot will return to bank, open bank but not deposit loot 
Current behavior: Triggers bank logic on full inv, returns to bank, opens bank, closes bank and returns to task
Expected behavior: Deposit items and return to task
Screenshot: None
Additional Information: If I pause bank the items and unpause script it will work
[logs_bankstuck.txt](https://github.com/PTYB/SlayerIssueTracker/files/11953753/logs_bankstuck.txt)

**Comment by PTYB** [comment]
Which blue dragons in which location?

**Comment by PTYB** [comment]
Do you have a full inventory?

**Comment by winslowcode** [comment]
I have a full inventory when this happens, Task is The Ogre Enclave Blue Dragons

**Comment by PTYB** [comment]
Forgot to reply, if you no room to loot/eat food it will bank.

**Comment by PTYB** [comment]
Closing, feel free to comment/reopen if this issue occurs again.
