### ISSUE TITLE
Kalphite forever loop bug

### ISSUE THREAD

**Issue by jaywalker15262** [PTYB/SlayerIssueTracker#84]
Issue: Goes to kalphites and back to bank forever in a loop.
Screenshot: None
Additional Information: Not much more to add, i do notice tho that it deposits shantay passes sometimes

**Comment by PTYB** [comment]
Need more info

**Comment by jaywalker15262** [comment]
I suspect it to be due to not bringing anti-venoms/poisons by default. Every user has to add it manually i think

**Comment by Rallik-Pog** [comment]
The script does not recognize Antidote++ in inventory, it goes to the bank once it gets poisoned.

**Comment by PTYB** [comment]
Create a new ticket please, this is closed and I will lose track. But I have pushed support for anti-venom and antidote++
