### ISSUE TITLE
[Bug][Website] Available list does not show all inventory groups

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#87]
Issue: Available list does not show all inventory groups.
Current behavior: 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/ea8983b3-c0c0-47d4-b04a-8c0f90502741)

Expected behavior: Show entire list from inventory groups. 
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/2777e6fb-6986-4da5-b147-21921ab975d4)

**Comment by Rallik-Pog** [comment]
https://github.com/PTYB/SlayerIssueTracker/assets/118016227/cfca204c-0d98-4510-91b4-24da931ef000

**Comment by PTYB** [comment]
Fixed now
