### ISSUE TITLE
[Bug] High Alchemy

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#88]
Issue: Does not click on the item it wants to high alch
Current behavior: Clicks high alchemy but does not click the item
Expected behavior: Click high alch and click the item
Screenshots/Video: I will DM you a video on discord.
Additional information:

[high alch logs.txt](https://github.com/PTYB/SlayerIssueTracker/files/12592338/high.alch.logs.txt)

**Comment by Rallik-Pog** [comment]
I believe it's misclicking the item it's supposed to high alch or it's not clicking at all.

**Comment by PTYB** [comment]
This was resolved right?

**Comment by Rallik-Pog** [comment]
Yes resolved. Thank you.
