### ISSUE TITLE
[Bug] Inventory Setup, endless loop at bank

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#89]
Issue:  Inventory Setup, endless loop at bank

Current behavior: It will fight with the general setup, for example Melee Prayer vs Specific setup for monster.

For the two screenshots below, it will endlessly deposit prayer potions to meet the specific setup, and withdraw prayer potions to meet the general melee prayer setup.

Expected behavior: Use the specific setup for monster instead of general setup.

Screenshots/Video:
General
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/ccc1a3da-4a30-4890-a709-e817a4f0fbb3)
Specific
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/63db32b5-42df-4611-b3a0-ab317b2435a6)
 
Additional information: We spoke about this over discord, I send you a video there.

**Comment by PTYB** [comment]
This was resolved right?

**Comment by Rallik-Pog** [comment]
This is not resolved.

**Comment by PTYB** [comment]
Can you give me a config id with this setup that replicates it please? Can't seem to replicate it.

**Comment by PTYB** [comment]
Found the issue I think, will address it after work today

**Comment by PTYB** [comment]
Could you please try again?

**Comment by PTYB** [comment]
Closing since 3 weeks @Rallik-Pog feel free to reopen if happens
