### ISSUE TITLE
[Bug] Kalphite Cave endless Loop

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#90]
Oh I just encountered this--- for some reason when its in the kalphite cave not the task cave it redoes a inventory check and senses its missing a rope (that it used to get in) so it goes back to grab another rope. it will also do this with food and potions.
It will randomly check inventory inside the lair and notice its missing the starting items since it drank a potion and goes back to bank.

[bug.txt](https://github.com/PTYB/SlayerIssueTracker/files/12622353/bug.txt)

**Comment by Djumi123** [comment]
Got the same bug. it just kills some Kalphite then runs back to the bank for no obvious reason.

**Comment by Rallik-Pog** [comment]
A fix was pushed, might be working now need to confirm

**Comment by Rallik-Pog** [comment]
fixed.
