### ISSUE TITLE
[Bug] Wyrm - Karuulm Slayer Dungeon

### ISSUE THREAD

**Issue by Djumi123** [PTYB/SlayerIssueTracker#91]
Issue: 
- Often does not make it through the dungeon alone / just afks on entrance

Current behavior:
- Does not run correctly through the dungeon

Expected behavior:
- Runs correctly through the dungeon

Screenshots/Video:
- None

Additional information:
- None

**Comment by PTYB** [comment]
Screenshot needed

**Comment by Rallik-Pog** [comment]
I had similar issues, there is a blind spot in dax where it doesnt know where it is.

**Comment by PTYB** [comment]
Closing @Rallik-Pog if you get raise an ew one
