### ISSUE TITLE
[BUG] Min gp value not working

### ISSUE THREAD

**Issue by Djumi123** [PTYB/SlayerIssueTracker#92]
Issue:

-  The "min. gp value" seems to have no influence?

Current behavior:

- Set the "min. gp value" to 1000, however it still picks up Lobster and other garbage from the ground.

Expected behavior:

- The "min. gp value" should prevent items below the specified value from being picked up.

Screenshots/Video:

- None

Additional information:

- None

**Comment by PTYB** [comment]
This was never implemented, was pushed accidently as part of another bug fix.

**Comment by PTYB** [comment]
It has been released now

**Comment by Djumi123** [comment]
Seems to be working now. good job man!

**Comment by PTYB** [comment]
Closing :)
