### ISSUE TITLE
[Bug][Website] Can´t delete inventory groups

### ISSUE THREAD

**Issue by Djumi123** [PTYB/SlayerIssueTracker#93]
Issue:

-  When I delete a custom item group in the inventory on the web page and click save, it is not deleted.

Current behavior:

- Cannot delete a self created item group in the inventory on the web page.

Expected behavior:

- Can delete self created item group in inventory on web page.

Screenshots/Video:

- None

Additional information:

- None

**Comment by PTYB** [comment]
By item group, do you mean the actual group or items inside the group?

**Comment by PTYB** [comment]
Closing, let me know if theres issues
