### ISSUE TITLE
[Enhancement] Empty herb sack when banking

### ISSUE THREAD

**Issue by Rallik-Pog** [PTYB/SlayerIssueTracker#94]
Empty herb sack when banking, that is all.

**Comment by Rallik-Pog** [comment]
![image](https://github.com/PTYB/SlayerIssueTracker/assets/118016227/b68c46eb-71a9-46a9-b73f-8c3b98663096)

**Comment by Rallik-Pog** [comment]
Works great, thank you.

**Comment by Rallik-Pog** [comment]
@PTYB Just noticed it emptys twice, once while depositing all items and again when it completes the inventory setup.

**Comment by PTYB** [comment]
Added a longer timer, so shouldnt happen again
