### ISSUE TITLE
Dies in Swamp Cave(Default Light source should be Candle Lantern)

### ISSUE THREAD

**Issue by Savage-FoL** [PTYB/SlayerIssueTracker#99]
Issue: Candle Lantern goes out and never gets lit back up
Current behavior: Bot goes over the Stepping stone and always falls in the water, candle lantern goes out and bot Dies
Expected behavior: Use the Tinderbox on the Candle lantern to light it back up
Screenshots/Video:
Additional information: This happens on the way to Rockslugs in Lumbridge Swamp Cave

**Comment by PTYB** [comment]
Vannaka isn't officially supported right now.

**Comment by PTYB** [comment]
Added default
